import type { OssTool } from "./types";

const MARKER = (slug: string) =>
    JSON.stringify(
        {
            sturdee_integration: slug,
            verified_by: "sturdee-opensource-hub",
            schema: 1,
        },
        null,
        2
    );

export const OSS_TOOLS: OssTool[] = [
    {
        slug: "react",
        name: "React",
        category: "Frontend",
        githubUrl: "https://github.com/facebook/react",
        website: "https://react.dev",
        license: "MIT",
        description: "Meta's UI library — powers Instagram, Netflix, and most modern SPAs.",
        stars: "230k+",
        points: 10,
        tags: ["ui", "components", "jsx"],
        installCommand: "npm install react react-dom",
        integrationGoal: "Create a reusable React component and export it.",
        steps: ["Install React", "Create Greeting.jsx component", "Export default component", "Commit and push to GitHub"],
        starterFiles: {
            "Greeting.jsx": `// Integrate React — export a Greeting component\nexport default function Greeting({ name }) {\n  return null;\n}\n`,
            "sturdee.integrations.json": MARKER("react"),
        },
        commitMessage: "feat: integrate react [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "nextjs",
        name: "Next.js",
        category: "Frontend",
        githubUrl: "https://github.com/vercel/next.js",
        website: "https://nextjs.org",
        license: "MIT",
        description: "Vercel's React framework with App Router, SSR, and edge deployment.",
        stars: "130k+",
        points: 12,
        tags: ["react", "ssr", "fullstack"],
        installCommand: "npx create-next-app@latest",
        integrationGoal: "Define an App Router page component with metadata export.",
        steps: ["Create page.tsx pattern", "Export metadata object", "Push integration branch"],
        starterFiles: {
            "page.tsx": `// Next.js App Router page integration\nexport const metadata = { title: "" };\n\nexport default function Page() {\n  return <main><h1></h1></main>;\n}\n`,
            "sturdee.integrations.json": MARKER("nextjs"),
        },
        commitMessage: "feat: integrate nextjs [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "tailwindcss",
        name: "Tailwind CSS",
        category: "Frontend",
        githubUrl: "https://github.com/tailwindlabs/tailwindcss",
        website: "https://tailwindcss.com",
        license: "MIT",
        description: "Utility-first CSS framework used by GitHub, Shopify, and Linear.",
        stars: "85k+",
        points: 8,
        tags: ["css", "design-system"],
        installCommand: "npm install tailwindcss @tailwindcss/postcss",
        integrationGoal: "Configure Tailwind and use utility classes in HTML.",
        steps: ["Add tailwind.config.js", "Use flex/grid utilities in index.html", "Push to GitHub"],
        starterFiles: {
            "tailwind.config.js": `/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: ["./index.html"],\n  theme: { extend: {} },\n  plugins: [],\n};\n`,
            "index.html": `<!DOCTYPE html>\n<html>\n<head><title>Tailwind Integration</title></head>\n<body class="">\n  <nav class=""></nav>\n</body>\n</html>\n`,
            "sturdee.integrations.json": MARKER("tailwindcss"),
        },
        commitMessage: "feat: integrate tailwindcss [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "vite",
        name: "Vite",
        category: "Frontend",
        githubUrl: "https://github.com/vitejs/vite",
        website: "https://vite.dev",
        license: "MIT",
        description: "Next-gen frontend build tool — instant HMR, used by Vue and React ecosystems.",
        stars: "72k+",
        points: 8,
        tags: ["bundler", "dev-server"],
        installCommand: "npm create vite@latest",
        integrationGoal: "Configure vite.config with a project name and base path.",
        steps: ["Create vite.config.js", "Set build.outDir", "Push config to GitHub"],
        starterFiles: {
            "vite.config.js": `import { defineConfig } from 'vite';\n\nexport default defineConfig({\n  // Configure your Vite integration\n});\n`,
            "sturdee.integrations.json": MARKER("vite"),
        },
        commitMessage: "feat: integrate vite [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "vue",
        name: "Vue.js",
        category: "Frontend",
        githubUrl: "https://github.com/vuejs/core",
        website: "https://vuejs.org",
        license: "MIT",
        description: "Progressive JavaScript framework — approachable core with scalable state management.",
        stars: "48k+",
        points: 10,
        tags: ["ui", "spa"],
        installCommand: "npm create vue@latest",
        integrationGoal: "Create a Vue SFC with script setup and template.",
        steps: ["Build Hello.vue SFC", "Use ref() for reactive state", "Push to GitHub"],
        starterFiles: {
            "Hello.vue": `<script setup>\nimport { ref } from 'vue';\nconst message = ref('');\n</script>\n<template>\n  <p></p>\n</template>\n`,
            "sturdee.integrations.json": MARKER("vue"),
        },
        commitMessage: "feat: integrate vue [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "express",
        name: "Express",
        category: "Backend",
        githubUrl: "https://github.com/expressjs/express",
        website: "https://expressjs.com",
        license: "MIT",
        description: "Minimal Node.js web framework — foundation of most Node APIs.",
        stars: "65k+",
        points: 10,
        tags: ["nodejs", "api", "http"],
        installCommand: "npm install express",
        integrationGoal: "Create an Express app with a GET /health route.",
        steps: ["Import express", "Add health endpoint returning JSON", "Push server.js"],
        starterFiles: {
            "server.js": `const express = require('express');\nconst app = express();\n\n// Add GET /health route\n\nmodule.exports = app;\n`,
            "sturdee.integrations.json": MARKER("express"),
        },
        commitMessage: "feat: integrate express [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "fastapi",
        name: "FastAPI",
        category: "Backend",
        githubUrl: "https://github.com/fastapi/fastapi",
        website: "https://fastapi.tiangolo.com",
        license: "MIT",
        description: "Modern Python API framework with automatic OpenAPI docs.",
        stars: "80k+",
        points: 10,
        tags: ["python", "api", "async"],
        installCommand: "pip install fastapi uvicorn",
        integrationGoal: "Define a FastAPI app with a /health endpoint.",
        steps: ["Create main.py", "Add @app.get('/health')", "Push to GitHub"],
        starterFiles: {
            "main.py": `from fastapi import FastAPI\n\napp = FastAPI()\n\n# Add health check route\n`,
            "sturdee.integrations.json": MARKER("fastapi"),
        },
        commitMessage: "feat: integrate fastapi [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "supabase",
        name: "Supabase",
        category: "Database",
        githubUrl: "https://github.com/supabase/supabase",
        website: "https://supabase.com",
        license: "Apache-2.0",
        description: "Open-source Firebase alternative — Postgres, Auth, Storage, Realtime.",
        stars: "75k+",
        points: 12,
        tags: ["postgres", "auth", "baas"],
        installCommand: "npm install @supabase/supabase-js",
        integrationGoal: "Initialize Supabase client with createClient pattern.",
        steps: ["Create supabase.js client module", "Export configured client", "Push to GitHub"],
        starterFiles: {
            "supabase.js": `import { createClient } from '@supabase/supabase-js';\n\nconst url = process.env.SUPABASE_URL;\nconst key = process.env.SUPABASE_ANON_KEY;\n\n// Export createClient instance\n`,
            "sturdee.integrations.json": MARKER("supabase"),
        },
        commitMessage: "feat: integrate supabase [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "postgresql",
        name: "PostgreSQL",
        category: "Database",
        githubUrl: "https://github.com/postgres/postgres",
        website: "https://postgresql.org",
        license: "PostgreSQL",
        description: "World's most advanced open-source relational database.",
        stars: "17k+",
        points: 10,
        tags: ["sql", "database"],
        installCommand: "docker run -d -p 5432:5432 postgres:16",
        integrationGoal: "Write a schema migration SQL file with a users table.",
        steps: ["Create migration SQL", "Define users table with id, email", "Push to GitHub"],
        starterFiles: {
            "001_users.sql": `-- PostgreSQL integration migration\n-- Create users table\n`,
            "sturdee.integrations.json": MARKER("postgresql"),
        },
        commitMessage: "feat: integrate postgresql [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "redis",
        name: "Redis",
        category: "Database",
        githubUrl: "https://github.com/redis/redis",
        website: "https://redis.io",
        license: "BSD-3",
        description: "In-memory data store for caching, sessions, and pub/sub.",
        stars: "68k+",
        points: 8,
        tags: ["cache", "key-value"],
        installCommand: "npm install redis",
        integrationGoal: "Configure Redis client connection with cache helper.",
        steps: ["Create redis.js client", "Add setCache/getCache helpers", "Push to GitHub"],
        starterFiles: {
            "redis.js": `// Redis integration — connection + cache helpers\nexport async function getCache(key) {\n  // implement\n}\n\nexport async function setCache(key, value, ttl) {\n  // implement\n}\n`,
            "sturdee.integrations.json": MARKER("redis"),
        },
        commitMessage: "feat: integrate redis [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "lodash",
        name: "Lodash",
        category: "Utilities",
        githubUrl: "https://github.com/lodash/lodash",
        website: "https://lodash.com",
        license: "MIT",
        description: "JavaScript utility library — chunk, debounce, cloneDeep used in every codebase.",
        stars: "60k+",
        points: 5,
        tags: ["utilities", "data"],
        installCommand: "npm install lodash",
        integrationGoal: "Use lodash chunk and uniq on a dataset.",
        steps: ["Import lodash", "Chunk array into groups of 3", "Push utils.js"],
        starterFiles: {
            "utils.js": `import chunk from 'lodash/chunk.js';\nimport uniq from 'lodash/uniq.js';\n\nexport function processPlaylist(trackIds) {\n  // Use chunk and uniq\n}\n`,
            "sturdee.integrations.json": MARKER("lodash"),
        },
        commitMessage: "feat: integrate lodash [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "axios",
        name: "Axios",
        category: "Utilities",
        githubUrl: "https://github.com/axios/axios",
        website: "https://axios-http.com",
        license: "MIT",
        description: "Promise-based HTTP client with interceptors — standard for API integration.",
        stars: "106k+",
        points: 6,
        tags: ["http", "api"],
        installCommand: "npm install axios",
        integrationGoal: "Create axios instance with baseURL and error interceptor.",
        steps: ["Configure axios.create", "Add response interceptor", "Push api.js"],
        starterFiles: {
            "api.js": `import axios from 'axios';\n\nconst client = axios.create({\n  baseURL: 'https://api.example.com',\n});\n\n// Add interceptor for errors\n\nexport default client;\n`,
            "sturdee.integrations.json": MARKER("axios"),
        },
        commitMessage: "feat: integrate axios [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "zod",
        name: "Zod",
        category: "Utilities",
        githubUrl: "https://github.com/colinhacks/zod",
        website: "https://zod.dev",
        license: "MIT",
        description: "TypeScript-first schema validation — used in tRPC, Next.js server actions.",
        stars: "37k+",
        points: 6,
        tags: ["validation", "typescript"],
        installCommand: "npm install zod",
        integrationGoal: "Define a Zod schema for user input and parse safely.",
        steps: ["Create userSchema with email", "Export parseUser function", "Push schema.js"],
        starterFiles: {
            "schema.js": `import { z } from 'zod';\n\n// Define user schema with email and name\n\nexport function parseUser(input) {\n  // parse and return\n}\n`,
            "sturdee.integrations.json": MARKER("zod"),
        },
        commitMessage: "feat: integrate zod [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "docker",
        name: "Docker",
        category: "DevOps",
        githubUrl: "https://github.com/docker/docs",
        website: "https://docker.com",
        license: "Apache-2.0",
        description: "Container platform — package apps with dependencies for any environment.",
        stars: "—",
        points: 10,
        tags: ["containers", "devops"],
        installCommand: "docker --version",
        integrationGoal: "Write a Dockerfile for a Node.js app.",
        steps: ["Create Dockerfile with node:22-alpine", "Set WORKDIR and CMD", "Push to GitHub"],
        starterFiles: {
            Dockerfile: `FROM node:22-alpine\nWORKDIR /app\n# Complete the Dockerfile integration\n`,
            "sturdee.integrations.json": MARKER("docker"),
        },
        commitMessage: "feat: integrate docker [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "github-actions",
        name: "GitHub Actions",
        category: "DevOps",
        githubUrl: "https://github.com/actions/starter-workflows",
        website: "https://github.com/features/actions",
        license: "MIT",
        description: "CI/CD built into GitHub — run tests on every push and PR.",
        stars: "—",
        points: 8,
        tags: ["ci", "cd", "automation"],
        installCommand: "mkdir -p .github/workflows",
        integrationGoal: "Create a workflow that runs npm test on push.",
        steps: ["Create ci.yml workflow", "Add node setup + npm test step", "Push to GitHub"],
        starterFiles: {
            ".github/workflows/ci.yml": `name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      # Add node + test steps\n`,
            "sturdee.integrations.json": MARKER("github-actions"),
        },
        commitMessage: "feat: integrate github-actions [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "vitest",
        name: "Vitest",
        category: "Testing",
        githubUrl: "https://github.com/vitest-dev/vitest",
        website: "https://vitest.dev",
        license: "MIT",
        description: "Vite-native unit test framework — fast, ESM-first, Jest-compatible API.",
        stars: "14k+",
        points: 7,
        tags: ["testing", "unit"],
        installCommand: "npm install -D vitest",
        integrationGoal: "Write a Vitest test file with describe/it/expect.",
        steps: ["Create sum.test.js", "Test a sum function", "Push to GitHub"],
        starterFiles: {
            "sum.js": `export function sum(a, b) {\n  return a + b;\n}\n`,
            "sum.test.js": `import { describe, it, expect } from 'vitest';\nimport { sum } from './sum.js';\n\n// Write tests for sum()\n`,
            "sturdee.integrations.json": MARKER("vitest"),
        },
        commitMessage: "feat: integrate vitest [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "jest",
        name: "Jest",
        category: "Testing",
        githubUrl: "https://github.com/jestjs/jest",
        website: "https://jestjs.io",
        license: "MIT",
        description: "Meta's JavaScript testing framework — default for React and Node projects.",
        stars: "44k+",
        points: 7,
        tags: ["testing", "unit"],
        installCommand: "npm install -D jest",
        integrationGoal: "Write Jest tests with describe/test/expect.",
        steps: ["Create greet.test.js", "Test greet function", "Push to GitHub"],
        starterFiles: {
            "greet.js": `export function greet(name) {\n  return '';\n}\n`,
            "greet.test.js": `import { greet } from './greet.js';\n\n// Write Jest tests\n`,
            "sturdee.integrations.json": MARKER("jest"),
        },
        commitMessage: "feat: integrate jest [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "prisma",
        name: "Prisma",
        category: "Database",
        githubUrl: "https://github.com/prisma/prisma",
        website: "https://prisma.io",
        license: "Apache-2.0",
        description: "Next-gen ORM for Node.js and TypeScript — type-safe database access.",
        stars: "40k+",
        points: 10,
        tags: ["orm", "postgres", "typescript"],
        installCommand: "npm install prisma @prisma/client",
        integrationGoal: "Define a Prisma schema with User model.",
        steps: ["Create schema.prisma", "Define User model", "Push to GitHub"],
        starterFiles: {
            "schema.prisma": `generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n// Define User model\n`,
            "sturdee.integrations.json": MARKER("prisma"),
        },
        commitMessage: "feat: integrate prisma [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "tensorflow",
        name: "TensorFlow",
        category: "AI/ML",
        githubUrl: "https://github.com/tensorflow/tensorflow",
        website: "https://tensorflow.org",
        license: "Apache-2.0",
        description: "Google's ML framework — training and deploying models at scale.",
        stars: "185k+",
        points: 12,
        tags: ["ml", "ai", "python"],
        installCommand: "pip install tensorflow",
        integrationGoal: "Create a simple tensor operation script.",
        steps: ["Import tensorflow", "Create and multiply tensors", "Push model.py"],
        starterFiles: {
            "model.py": `import tensorflow as tf\n\n# Create two tensors and compute their dot product\n`,
            "sturdee.integrations.json": MARKER("tensorflow"),
        },
        commitMessage: "feat: integrate tensorflow [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
    {
        slug: "playwright",
        name: "Playwright",
        category: "Testing",
        githubUrl: "https://github.com/microsoft/playwright",
        website: "https://playwright.dev",
        license: "Apache-2.0",
        description: "Microsoft's E2E testing framework — cross-browser automation.",
        stars: "68k+",
        points: 9,
        tags: ["e2e", "testing"],
        installCommand: "npm init playwright@latest",
        integrationGoal: "Write a Playwright test that checks page title.",
        steps: ["Create example.spec.js", "Use page.goto and expect title", "Push to GitHub"],
        starterFiles: {
            "example.spec.js": `import { test, expect } from '@playwright/test';\n\ntest('homepage', async ({ page }) => {\n  // Navigate and assert title\n});\n`,
            "sturdee.integrations.json": MARKER("playwright"),
        },
        commitMessage: "feat: integrate playwright [sturdee]",
        markerFile: "sturdee.integrations.json",
    },
];

export function getOssTool(slug: string): OssTool | undefined {
    return OSS_TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): OssTool[] {
    return OSS_TOOLS.filter((t) => t.category === category);
}

export function getAllCategories(): string[] {
    return [...new Set(OSS_TOOLS.map((t) => t.category))];
}

export const OSS_TOOL_COUNT = OSS_TOOLS.length;
export const MAX_OSS_POINTS = OSS_TOOLS.reduce((sum, t) => sum + t.points, 0);
