import { section, h2, h3, list, page, code, tryit, p, note, tip, steps } from "../builder";

const ext = "liquid";

export const liquidBasicsSection = section("Liquid Basics", [
    page("liquid_intro", "Liquid Introduction", [
        h2("What is Liquid?"),
        p("Liquid is an open-source templating language created by Shopify in 2006. Unlike PHP or Ruby, Liquid does not execute arbitrary code on the server. Instead, it provides a strict, sandboxed vocabulary of tags, objects, and filters that transform templates into HTML before the response is sent to the browser."),
        p("When a customer visits your Shopify store, Shopify's servers read your theme files (.liquid, .json), merge them with live store data (products, prices, cart contents, customer session), and output plain HTML. The customer never sees Liquid syntax — only the rendered result."),
        h2("Why Shopify Uses Liquid"),
        p("Shopify hosts thousands of merchants on shared infrastructure. Liquid's sandbox prevents theme developers from opening files, running shell commands, or accessing other stores' data. This security model is why every Shopify theme — from free themes to enterprise custom builds — is built with Liquid at its core."),
        list([
            "Safe by design — merchants cannot break server security with theme code",
            "Separates presentation (HTML/CSS) from store data (products, orders)",
            "Readable by non-developers — merchants can edit text in the theme editor",
            "Extensible — Shopify adds objects like product, cart, and routes for commerce",
        ]),
        h2("Liquid in the Theme Rendering Pipeline"),
        steps([
            "Shopify receives an HTTP request (e.g. GET /products/web-development-course)",
            "The router selects a template (templates/product.json) and loads its sections",
            "Each section file (.liquid) is processed: tags run logic, {{ }} outputs values",
            "The layout (layout/theme.liquid) wraps the page with header, footer, and assets",
            "Final HTML is sent to the browser; JavaScript may enhance the page client-side",
        ]),
        h3("Your First Liquid Output"),
        code(ext, `{% comment %}\n  Comments are stripped before render.\n  Use them to document complex logic for other developers.\n{% endcomment %}\n\n<h1>Welcome to {{ shop.name }}</h1>\n<p>{{ shop.description }}</p>\n<p>Currency: {{ shop.currency }} · Domain: {{ shop.domain }}</p>`, "Store branding with the global shop object"),
        p("The shop object is available on every page of your theme. shop.name returns the store title from Shopify Admin → Settings → Store details. shop.currency returns the ISO currency code (e.g. USD, EUR) used for money filters."),
        tryit("html", `<h1>Welcome to Sturdee Store</h1>\n<p>Premium courses and tutorials for developers.</p>\n<p>Currency: USD · Domain: sturdee.myshopify.com</p>`),
        tip("Bookmark the official Shopify Liquid reference at shopify.dev/docs/api/liquid — it lists every object, tag, and filter with up-to-date definitions."),
    ]),
    page("liquid_syntax", "Liquid Syntax", [
        h2("The Three Delimiter Types"),
        p("Every Liquid template uses exactly three kinds of delimiters. Understanding when to use each one is the foundation of all theme development."),
        list([
            "{{ }} — Output: evaluates an expression and prints the result into the HTML stream",
            "{% %} — Logic tags: control flow, loops, variable assignment, and includes — produce no direct output",
            "{% comment %} ... {% endcomment %} — Comments: removed entirely before rendering; visible only in source files",
        ]),
        h3("Output Tags {{ }}"),
        p("Output tags wrap a Liquid expression. Shopify evaluates the expression, converts it to a string, and inserts it at that position in the HTML. You can chain filters inside output tags using the pipe character."),
        code(ext, `{{ product.title }}\n{{ product.price | money }}\n{{ product.description | strip_html | truncate: 160 }}`, "Output with chained filters"),
        steps([
            "product.title — accesses the title property of the product object on a product page",
            "| money — filter formats the integer price (cents) as localized currency ($18.99)",
            "| strip_html — removes HTML tags from the description before display",
            "| truncate: 160 — limits text to 160 characters with an ellipsis",
        ]),
        h3("Logic Tags {% %}"),
        p("Logic tags implement conditionals, loops, and template composition. They never print text directly — they control what surrounding HTML is included in the output."),
        code(ext, `{% if product.available %}\n  <button type="submit" name="add" class="btn btn--primary">\n    Add to cart\n  </button>\n{% else %}\n  <p class="stock-status stock-status--sold-out">Sold out</p>\n{% endif %}`, "Conditional add-to-cart button"),
        p("Here, product.available is a boolean Shopify sets based on inventory. If any variant has stock (or inventory tracking is off), it returns true. The {% else %} branch renders when every variant is unavailable."),
        h3("Whitespace Control"),
        p("Liquid preserves whitespace by default. In tightly packed HTML (especially inline elements), extra newlines can cause layout bugs. Use hyphens inside delimiters to strip whitespace: {%- tag -%} or {{- variable -}}."),
        code(ext, `{%- if collection.products.size > 0 -%}\n  <div class="grid">{%- endif -%}`, "Strip whitespace around tags"),
        note("Theme Check will warn about missing whitespace control in performance-sensitive templates. Use {%- liquid -%} blocks to group multiple assignments on separate lines with minimal output whitespace."),
        tryit("html", `<button type="submit" class="btn btn--primary">Add to cart</button>`),
    ]),
    page("liquid_variables", "Liquid Variables", [
        h2("Creating Variables with assign"),
        p("Variables let you store intermediate values and keep templates readable. The {% assign %} tag creates a variable in the current scope. Liquid variables are dynamically typed — you do not declare types."),
        p("Allowed value types: strings, numbers, booleans, nil, arrays, and Liquid drops (Shopify objects). You cannot assign complex Ruby objects or execute functions with assign — only expressions."),
        code(ext, `{% assign greeting = "Hello" %}\n{% assign on_sale = false %}\n{% assign max_items = 4 %}\n\n{% if customer %}\n  <p>{{ greeting }}, {{ customer.first_name }}!</p>\n{% else %}\n  <p>{{ greeting }}, guest!</p>\n{% endif %}`, "assign for reusable strings and flags"),
        h3("capture — Store Rendered HTML"),
        p("The {% capture %} tag executes everything inside it (including other Liquid tags and HTML), captures the resulting string, and stores it in a variable. This is essential for building HTML fragments you output in multiple places or pass to snippets."),
        code(ext, `{% capture sale_badge %}\n  {% if product.compare_at_price > product.price %}\n    <span class="badge badge--sale">\n      Save {{ product.compare_at_price | minus: product.price | money }}\n    </span>\n  {% endif %}\n{% endcapture %}\n\n{{ sale_badge }}`, "Capture conditional HTML into a variable"),
        p("Without capture, you would duplicate the if block everywhere you need the badge. Capture runs the inner template once and stores the result — including an empty string if the condition is false."),
        h3("increment and decrement"),
        p("These tags create a counter variable in the parent scope, starting at 0. Each call to {% increment var %} returns the current value then adds 1. Useful for zebra-striping rows without manual index math."),
        code(ext, `{% for item in cart.items %}\n  <tr class="row-{% increment row_counter %}">\n    <td>{{ item.product.title }}</td>\n  </tr>\n{% endfor %}`, "Auto-incrementing row class"),
        note("assign creates or overwrites variables. increment/decrement only work with numeric counters and persist across the template render within the same scope."),
    ]),
    page("liquid_data_types", "Liquid Data Types", [
        h2("Understanding Liquid Types"),
        p("Liquid is dynamically typed. You do not declare types, but knowing how Shopify represents data prevents subtle bugs — especially when comparing values in {% if %} tags or passing data to JavaScript."),
        list([
            "String — text in single or double quotes: \"Hello\" or 'World'",
            "Number — integers and decimals: 42, 3.14. Money is stored as integers in cents (1899 = $18.99)",
            "Boolean — true or false (lowercase only in Liquid comparisons)",
            "Nil — represents empty/missing values; falsy in conditionals",
            "Array — ordered lists: product.images, cart.items, collection.products",
            "Object (Drop) — Shopify wrappers: product, collection, shop — expose properties and methods",
        ]),
        h3("Truthy and Falsy Values"),
        p("In {% if %} tags, nil and false are falsy. Empty strings, zero, and empty arrays are truthy in Liquid (unlike JavaScript). Always compare explicitly when checking for empty collections."),
        code(ext, `{% if product == nil %}\n  <p>Product not found — check the handle or publish status.</p>\n{% endif %}\n\n{% if collection.products.size > 0 %}\n  <p>Showing {{ collection.products.size }} of {{ collection.all_products_count }} products</p>\n{% else %}\n  <p>No products in this collection yet.</p>\n{% endif %}`, "Explicit nil and size checks"),
        tip("Use | default: 'fallback' on output tags when a metafield or setting might be blank, so merchants never see empty UI gaps."),
    ]),
    page("liquid_operators", "Liquid Operators", [
        h2("Comparison Operators"),
        p("Liquid supports standard comparisons inside {% if %}, {% unless %}, and {% case %} tags. Operands can be variables, object properties, or literals."),
        list([
            "== equal · != not equal",
            "< less than · > greater than · <= · >=",
            "contains — checks if a string includes a substring, or an array includes an item",
            "and · or — combine multiple conditions",
        ]),
        h3("Working with Money and Tags"),
        p("Product prices in Liquid are integers in the store's smallest currency unit (cents for USD). Compare numeric prices directly. For product tags, use contains — tags are an array of strings assigned in Shopify Admin."),
        code(ext, `{% if product.price < 5000 and product.available %}\n  <span class="badge badge--budget">Under $50</span>\n{% endif %}\n\n{% if product.tags contains 'bestseller' %}\n  <span class="badge badge--bestseller">Bestseller</span>\n{% endif %}\n\n{% if product.tags contains 'sale' or product.compare_at_price > product.price %}\n  <span class="badge badge--sale">On sale</span>\n{% endif %}`, "Price thresholds and tag-based badges"),
        p("The contains operator is case-sensitive for tags. Normalize tags in Admin (lowercase, hyphenated) to avoid mismatches like 'Sale' vs 'sale'."),
        note("Never compare money formatted strings (| money output). Always compare raw integer prices from product.price or variant.price."),
    ]),
]);
