import { section, h2, h3, list, page, code, tryit, p, note, tip, steps } from "../builder";

export const liquidCliSection = section("Shopify CLI", [
    page("shopify_cli_intro", "Shopify CLI Introduction", [
        h2("The Modern Theme Development Toolchain"),
        p("Shopify CLI (@shopify/cli + @shopify/theme) is the official command-line interface for theme and app development. It replaced Theme Kit and the deprecated shopify-themekit gem. CLI handles authentication, file sync, local preview, linting, and deployment — all from your terminal."),
        h3("What CLI Does"),
        list([
            "Scaffold new themes from Skeleton or clone Dawn",
            "Run shopify theme dev — live preview with hot reload on a development theme",
            "Push and pull theme files between local disk and a Shopify store",
            "Run Theme Check — static analysis for Liquid errors and performance issues",
            "Package themes for Theme Store submission",
            "Manage Shopify app development (extensions, deployment) — beyond themes",
        ]),
        steps([
            "Install Node.js 18+ and Shopify CLI via npm or Homebrew",
            "Authenticate with shopify auth login against a Partner dev store",
            "Clone or init a theme locally, run shopify theme dev",
            "Edit Liquid/CSS/JS — saves auto-sync to the dev theme",
            "Commit with Git, push to staging theme, then production",
        ]),
        note("Never develop directly on a live theme. CLI creates ephemeral development themes for shopify theme dev that are safe to overwrite."),
        tip("Install the Shopify Liquid VS Code extension alongside CLI for syntax highlighting, autocomplete, and inline Theme Check diagnostics."),
    ]),
    page("shopify_cli_install", "Install Shopify CLI", [
        h2("Installation Methods"),
        p("Shopify CLI is distributed as an npm package. Install both @shopify/cli (core) and @shopify/theme (theme commands) for full theme development support."),
        code("bash", `# Recommended: install globally via npm\nnpm install -g @shopify/cli @shopify/theme\n\n# Verify both packages\nshopify version\n\n# Update to latest\nnpm update -g @shopify/cli @shopify/theme`),
        h3("macOS — Homebrew"),
        code("bash", `brew tap shopify/shopify\nbrew install shopify-cli`),
        h3("System Requirements"),
        list([
            "Node.js 18.0.0 or higher (LTS recommended)",
            "npm, yarn, or pnpm for package management",
            "Git for version control (strongly recommended)",
            "A Shopify Partner account OR staff access to a store",
            "Modern browser for OAuth login during shopify auth login",
        ]),
        p("On Windows, use PowerShell or WSL. CLI works natively on Windows 10+ with Node installed. If you hit permission errors with global npm installs, use nvm-windows to manage Node versions or configure a user-level npm prefix."),
        note("WSL2 is preferred for Windows theme development — file watching and symlinks behave more reliably than native Windows in some setups."),
    ]),
    page("shopify_cli_auth", "CLI Authentication", [
        h2("Connecting CLI to Your Store"),
        p("shopify auth login opens a browser OAuth window. You log in with your Partner account or store staff credentials. CLI stores a session token locally so subsequent commands do not require re-login until expiry."),
        code("bash", `# Interactive login — pick store from list\nshopify auth login\n\n# Target a specific store directly\nshopify auth login --store your-dev-store.myshopify.com\n\n# Check current session\nshopify whoami\n\n# Clear credentials (switch accounts)\nshopify auth logout`),
        steps([
            "Create a development store in partners.shopify.com → Stores → Add store",
            "Development stores are free, support test payments, and are isolated from production",
            "Grant yourself 'Themes' permission on client stores before running theme commands",
            "Partner staff use Organizations — ensure you are in the correct Partner team",
        ]),
        tip("For CI/CD pipelines, use Theme Access passwords or the Shopify Admin API with a custom app — not interactive auth login."),
    ]),
    page("shopify_cli_theme_init", "theme init — Start a New Theme", [
        h2("Scaffolding a Theme Project"),
        p("shopify theme init creates a new directory with the full Online Store 2.0 folder structure. By default it clones Shopify's Skeleton reference theme — a minimal, educational starting point."),
        code("bash", `# Create from Skeleton (default)\nshopify theme init my-custom-theme\ncd my-custom-theme\n\n# Clone Dawn — Shopify's production reference theme\nshopify theme init my-dawn-theme \\\n  --clone-url https://github.com/Shopify/dawn.git\n\n# Initialize git immediately\n git init\ngit add .\ngit commit -m "Initial theme from Dawn"`),
        p("After init, you have assets/, config/, layout/, locales/, sections/, snippets/, and templates/. Open the folder in VS Code, install the Shopify Liquid extension, and run shopify theme dev to start developing."),
        list([
            "Skeleton — minimal, best for learning and greenfield projects",
            "Dawn — full-featured, best for production forks and pattern reference",
            "Horizon — newer Shopify reference theme (check Shopify GitHub for latest)",
        ]),
        note("Do not fork Dawn and submit it unchanged to the Theme Store. Shopify requires substantial differentiation for approval."),
    ]),
    page("shopify_cli_theme_dev", "theme dev — Local Development", [
        h2("Live Preview with Hot Reload"),
        p("shopify theme dev is the core daily workflow command. It uploads your local theme to a temporary development theme on your store, prints a preview URL, and watches files for changes. On save, CLI syncs the changed file and triggers a browser refresh."),
        code("bash", `cd my-theme\n\n# Start dev server\nshopify theme dev --store your-store.myshopify.com\n\n# Output example:\n# Preview: https://your-store.myshopify.com/?preview_theme_id=123456789\n# Shareable: https://your-store.myshopify.com/?preview_theme_id=123456789\n# (Ctrl+C to stop)`),
        h3("Useful Flags"),
        list([
            "--store — target .myshopify.com domain",
            "--theme THEME_ID — sync to an existing theme instead of creating a dev theme",
            "--only sections — sync only the sections/ folder (faster for large themes)",
            "--ignore config/settings_data.json — don't overwrite merchant editor changes",
            "--host 127.0.0.1 — local proxy configuration",
            "--port 9292 — custom local server port",
        ]),
        code("bash", `# Fast iteration: only sync Liquid partials\nshopify theme dev \\\n  --store your-store.myshopify.com \\\n  --only sections \\\n  --only snippets \\\n  --only layout`),
        steps([
            "Run theme dev in one terminal tab — leave it running all day",
            "Edit files in your editor — save triggers sync within 1-2 seconds",
            "Test on the preview URL — cart and checkout work with test payments",
            "Use browser DevTools for CSS/JS; use Liquid comments for template debugging",
        ]),
        tip("Add config/settings_data.json to .gitignore if multiple developers share a store — each dev's editor settings conflict otherwise."),
    ]),
    page("shopify_cli_theme_push", "theme push & pull", [
        h2("Deploying Theme Files to Shopify"),
        p("shopify theme push uploads local files to a remote theme. shopify theme pull downloads remote files to local. Use pull when a merchant edited the theme in Admin and you need to reconcile, or when taking over an existing store."),
        code("bash", `# List all themes on the store\nshopify theme list --store your-store.myshopify.com\n\n# Push to a NEW unpublished theme (safest for staging)\nshopify theme push \\\n  --store your-store.myshopify.com \\\n  --unpublished \\\n  --theme \"Staging v2\"\n\n# Push to an existing theme by ID\nshopify theme push \\\n  --store your-store.myshopify.com \\\n  --theme 123456789012\n\n# Push and publish live (DANGEROUS — prompts for confirmation)\nshopify theme push --store your-store.myshopify.com --publish\n\n# Pull remote theme to local\nshopify theme pull \\\n  --store your-store.myshopify.com \\\n  --theme 123456789012`),
        h3("Deployment Safety"),
        steps([
            "Always test on a development or unpublished theme first",
            "Run shopify theme check locally before every push",
            "Use --only and --ignore to push specific files during hotfixes",
            "Never push directly to live during business hours without a rollback plan",
            "Keep Git tags matching each production push for quick revert",
        ]),
        code("bash", `# Push only changed sections (hotfix)\nshopify theme push \\\n  --only sections/header.liquid \\\n  --theme LIVE_THEME_ID`),
        note("theme push overwrites remote files. It does not delete remote files that you deleted locally unless you use --nodelete false. Understand the flags before scripting deploys."),
    ]),
    page("shopify_cli_theme_check", "theme check — Linting", [
        h2("Static Analysis with Theme Check"),
        p("Theme Check scans your theme for Liquid syntax errors, deprecated tags, accessibility issues, and performance anti-patterns. It runs locally via CLI and in CI pipelines. Many Shopify Theme Store requirements map directly to Theme Check rules."),
        code("bash", `# Run all checks\nshopify theme check\n\n# List available checks\nshopify theme check --list\n\n# Auto-fix safe issues (deprecated filters, etc.)\nshopify theme check --auto-correct\n\n# Fail CI on errors only\nshopify theme check --fail-level error\n\n# Run specific check\nshopify theme check --include UndefinedObject`),
        h3("Common Violations"),
        list([
            "Missing {{ content_for_header }} in layout/theme.liquid",
            "Deprecated {% include %} — migrate to {% render %}",
            "Parser-blocking <script> in <head> without async/defer",
            "img tags missing width and height attributes",
            "Hardcoded /cart and /account URLs instead of routes",
            "Unused snippets, locales, and assign variables",
            "RemoteAsset — loading assets from non-Shopify CDNs",
        ]),
        p("Fix Theme Check errors before theme push. Warnings (performance suggestions) should be addressed for Theme Store submission but may be acceptable for custom client themes."),
        tip("Add a .theme-check.yml config to disable rules that do not apply to your project, but document why each disabled rule is intentional."),
    ]),
    page("shopify_cli_theme_package", "theme package & share", [
        h2("Distribution and Preview Links"),
        p("shopify theme package creates a .zip archive validated for Theme Store submission. shopify theme share generates a shareable preview link for client review without publishing."),
        code("bash", `# Create submission zip\nshopify theme package\n# Output: my-theme-1.0.0.zip in project root\n\n# Share preview link (expires)\nshopify theme share --store your-store.myshopify.com\n\n# Share a specific theme\nshopify theme share --theme 123456789012`),
        steps([
            "Run theme check — zero errors required for Theme Store",
            "Run theme package — CLI validates zip structure",
            "Submit zip via Partner Dashboard → Themes",
            "Use theme share for client approvals before publish",
        ]),
        note("Theme Store themes must include documentation, support contact, and meet accessibility and performance benchmarks beyond Theme Check."),
    ]),
    page("shopify_cli_github", "CLI + Git Workflow", [
        h2("Professional Theme Development Workflow"),
        p("Pair Git version control with Shopify CLI for team collaboration, code review, and safe deployments. Each environment (dev, staging, production) maps to a different Shopify theme on the same or different stores."),
        code("bash", `# ── Initial setup ──\ngit init\ngit add .\ngit commit -m "Initial theme scaffold"\ngit remote add origin git@github.com:your-org/your-theme.git\ngit push -u origin main\n\n# ── Daily development ──\ngit checkout -b feature/hero-section\nshopify theme dev --store dev-store.myshopify.com\n# ... edit sections/hero-banner.liquid ...\ngit add sections/hero-banner.liquid\ngit commit -m "Add hero banner section with video support"\ngit push origin feature/hero-section\n# Open PR for review\n\n# ── Deploy to staging ──\ngit checkout main\ngit pull\nshopify theme push \\\n  --store dev-store.myshopify.com \\\n  --unpublished \\\n  --theme \"Staging\"\n\n# ── Deploy to production (after QA sign-off) ──\nshopify theme push \\\n  --store production-store.myshopify.com \\\n  --theme PROD_THEME_ID\n\ngit tag v1.2.0\ngit push origin v1.2.0`),
        list([
            "main branch → production theme (protected, PR-only merges)",
            "develop branch → staging theme on dev store",
            "Feature branches → shopify theme dev ephemeral themes",
            "Tag releases matching shopify theme push deploys",
            "GitHub Actions can run theme check on every PR",
        ]),
        tip("Store THEME_IDs in environment variables or a deploy config — never hardcode production IDs in package.json scripts committed to public repos."),
    ]),
]);
