import { section, h2, h3, list, page, code, tryit, p, note, tip, steps } from "../builder";

export const liquidCliSection = section("Shopify CLI", [
    page("shopify_cli_intro", "Shopify CLI Introduction", [
        h2("The Modern Theme Development Toolchain"),
        p("Shopify CLI (@shopify/cli + @shopify/theme) is the official command-line interface for theme and app development. It replaced Theme Kit and the deprecated shopify-themekit gem. CLI handles authentication, file sync, local preview, linting, and deployment — all from your terminal."),
        h3("What CLI Does"),
        list([
            "Scaffold new themes from Skeleton or clone Dawn",
            "Run shopify theme dev — live preview with hot reload on a development theme",
            "Push and pull theme files between local disk and a Shopify store",
            "Run Theme Check — static analysis for Liquid errors and performance issues",
            "Package themes for Theme Store submission",
            "Manage Shopify app development (extensions, deployment) — beyond themes",
        ]),
        steps([
            "Install Node.js 22 LTS, Git, and Shopify CLI (see Install Shopify CLI page)",
            "Verify with node -v, npm -v, git --version, and shopify version",
            "Authenticate with shopify auth login against a Partner dev store",
            "Pull or init a theme locally, then run shopify theme dev",
            "Edit Liquid/CSS/JS in VS Code — saves auto-sync to the dev theme",
            "Commit with Git, push to staging theme, then production",
        ]),
        note("Never develop directly on a live theme. CLI creates ephemeral development themes for shopify theme dev that are safe to overwrite."),
        tip("Install the Shopify Liquid VS Code extension alongside CLI for syntax highlighting, autocomplete, and inline Theme Check diagnostics."),
    ]),
    page("shopify_cli_install", "Install Shopify CLI", [
        h2("Local Setup Overview"),
        p("To develop Shopify themes on your computer, you need three tools installed and verified before anything else: Node.js (includes npm), Git, and Shopify CLI. This page walks through checking what you already have, installing anything missing on Windows, and confirming your environment is ready."),
        p("Open PowerShell or Windows Terminal as a normal user (Administrator only if a package manager asks for it). Run each verification command in order — do not skip straight to Shopify CLI if Node or Git is missing."),
        h3("Step 1 — Check if Node.js is Installed"),
        p("Node.js runs Shopify CLI and powers the theme dev server. npm (Node Package Manager) ships with Node and is how you install Shopify CLI globally."),
        code("bash", `node -v\nnpm -v`, "Check Node and npm versions"),
        p("If both commands print version numbers, Node is installed. Write down what you see — you will compare against the expected versions at the end of this page."),
        p("If you see 'command not found' or 'not recognized', Node is not installed or not on your PATH. Install it using one of the methods below, then restart your terminal completely before running node -v again."),
        h3("Install Node.js (Windows)"),
        p("Pick one package manager. Chocolatey requires Chocolatey itself to be installed first (chocolatey.org). Winget ships with Windows 10/11 and is the simplest option for most developers."),
        code("bash", `# Option A — Chocolatey\nchoco install nodejs-lts -y\n\n# Option B — Winget (recommended on Windows)\nwinget install OpenJS.NodeJS.LTS`, "Install Node.js LTS on Windows"),
        steps([
            "Close and reopen your terminal after installation — PATH updates only apply to new sessions",
            "Run node -v and npm -v again to confirm",
            "If versions still do not appear, reboot Windows once",
        ]),
        h3("Step 2 — Install Git"),
        p("Git tracks theme file changes locally and lets you collaborate with teams. Shopify CLI works without Git, but every professional theme workflow uses it."),
        code("bash", `winget install Git.Git\n\n# Verify\ngit --version`, "Install and verify Git"),
        p("After install, restart the terminal. You should see something like git version 2.x.x. Configure your name and email once: git config --global user.name \"Your Name\" and git config --global user.email \"you@example.com\"."),
        h3("Step 3 — Install Shopify CLI"),
        p("Shopify CLI is installed globally through npm. Use @latest so you always get the current 3.x release with theme commands built in."),
        code("bash", `npm install -g @shopify/cli@latest\n\n# Verify\nshopify version`, "Install Shopify CLI globally"),
        p("If npm reports permission errors on Windows, close the terminal, reopen as Administrator, and retry. Alternatively, fix npm's global directory permissions rather than using sudo-style workarounds on every install."),
        note("Older guides mention installing @shopify/theme separately. On current Shopify CLI 3.x, theme commands (dev, push, pull, check) are included in @shopify/cli — one global install is enough."),
        h3("Step 4 — Log In to Shopify"),
        p("Before pulling or developing a theme, authenticate CLI with your Partner account or store staff login. This opens your browser for OAuth — complete the login there, then return to the terminal."),
        code("bash", `shopify auth login`, "Authenticate with Shopify"),
        p("To target a specific store immediately: shopify auth login --store your-store.myshopify.com. Run shopify whoami anytime to confirm which account is active."),
        h3("Step 5 — Clone an Existing Theme"),
        p("If the store already has a theme (Dawn, a custom build, or a client theme), pull it to your machine instead of starting from scratch."),
        code("bash", `# Download theme files from a store\nshopify theme pull --store your-store.myshopify.com\n\n# Pull a specific theme by ID (from shopify theme list)\nshopify theme pull --store your-store.myshopify.com --theme 123456789012`, "Pull remote theme to local folder"),
        p("This creates a folder with assets/, sections/, snippets/, templates/, and config/ — the full Online Store 2.0 structure. cd into that folder before running theme dev."),
        h3("Step 6 — Run the Local Development Server"),
        p("shopify theme dev uploads your local files to a hidden development theme and gives you a preview URL with hot reload. Leave this command running in a terminal tab while you edit in VS Code."),
        code("bash", `shopify theme dev --store your-store.myshopify.com`, "Start local development with hot reload"),
        p("When theme dev is running you get:"),
        list([
            "Hot reload — CSS and section changes refresh the browser automatically",
            "A local preview URL — test cart, product pages, and Liquid output with real store data",
            "Full VS Code editing — install the Shopify Liquid extension for syntax highlighting",
            "Custom Liquid development — every .liquid file you save syncs to the dev theme within seconds",
        ]),
        h3("Step 7 — Push Changes Back to Shopify"),
        p("When you are ready to upload local changes, use theme push. Never push directly to the live theme without testing on a development or unpublished theme first."),
        code("bash", `# Push to current directory's linked theme\nshopify theme push --store your-store.myshopify.com\n\n# Safer: push to a new unpublished staging theme\nshopify theme push --store your-store.myshopify.com --unpublished --theme "Staging"`, "Upload local files to Shopify"),
        h2("My Typical Setup — Verification Checklist"),
        p("After completing installation, run all four commands in one terminal session. Compare your output to the expected ranges below."),
        code("bash", `node -v\nnpm -v\ngit --version\nshopify version`, "Full environment check"),
        list([
            "Node v22.x (or latest LTS) — e.g. v22.14.0",
            "npm 10.x or higher — e.g. 10.9.2",
            "Git 2.x or higher — e.g. git version 2.47.0",
            "Shopify CLI 3.x or higher — e.g. 3.84.0",
        ]),
        h3("Fixing Node Version Conflicts with NVM (Windows)"),
        p("If you previously installed Node and get build errors, permission issues, or version conflicts with Shopify CLI, use NVM for Windows to manage multiple Node versions side by side. Node 22 LTS is currently the safest choice for Shopify theme development and custom Liquid themes."),
        code("bash", `# Install NVM for Windows\nwinget install CoreyButler.NVMforWindows\n\n# Restart terminal, then:\nnvm install 22\nnvm use 22\nnode -v`, "Switch to Node 22 LTS with NVM"),
        steps([
            "nvm install 22 downloads and installs Node 22 LTS",
            "nvm use 22 activates it for the current terminal session",
            "Re-run npm install -g @shopify/cli@latest after switching Node versions",
            "Run shopify version to confirm CLI still works on the new Node version",
        ]),
        h3("macOS & Linux (Quick Reference)"),
        code("bash", `# macOS — Node via Homebrew\nbrew install node\n\n# macOS — Shopify CLI\nbrew tap shopify/shopify\nbrew install shopify-cli\n\n# Linux / macOS — Node via nvm\ncurl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash\nnvm install 22\nnvm use 22`, "Alternative install paths"),
        tip("Install the Shopify Liquid VS Code extension after CLI setup. It adds syntax highlighting, autocomplete, and inline Theme Check warnings as you edit .liquid files."),
        note("WSL2 on Windows is an alternative if native file watching causes issues — install Node, Git, and CLI inside your Linux distro and store theme files in the Linux filesystem, not /mnt/c/."),
    ]),
    page("shopify_cli_auth", "CLI Authentication", [
        h2("Connecting CLI to Your Store"),
        p("shopify auth login opens a browser OAuth window. You log in with your Partner account or store staff credentials. CLI stores a session token locally so subsequent commands do not require re-login until expiry."),
        code("bash", `# Interactive login — pick store from list\nshopify auth login\n\n# Target a specific store directly\nshopify auth login --store your-dev-store.myshopify.com\n\n# Check current session\nshopify whoami\n\n# Clear credentials (switch accounts)\nshopify auth logout`),
        steps([
            "Create a development store in partners.shopify.com → Stores → Add store",
            "Development stores are free, support test payments, and are isolated from production",
            "Grant yourself 'Themes' permission on client stores before running theme commands",
            "Partner staff use Organizations — ensure you are in the correct Partner team",
        ]),
        tip("For CI/CD pipelines, use Theme Access passwords or the Shopify Admin API with a custom app — not interactive auth login."),
    ]),
    page("shopify_cli_theme_init", "theme init — Start a New Theme", [
        h2("Scaffolding a Theme Project"),
        p("shopify theme init creates a new directory with the full Online Store 2.0 folder structure. By default it clones Shopify's Skeleton reference theme — a minimal, educational starting point."),
        code("bash", `# Create from Skeleton (default)\nshopify theme init my-custom-theme\ncd my-custom-theme\n\n# Clone Dawn — Shopify's production reference theme\nshopify theme init my-dawn-theme \\\n  --clone-url https://github.com/Shopify/dawn.git\n\n# Initialize git immediately\n git init\ngit add .\ngit commit -m "Initial theme from Dawn"`),
        p("After init, you have assets/, config/, layout/, locales/, sections/, snippets/, and templates/. Open the folder in VS Code, install the Shopify Liquid extension, and run shopify theme dev to start developing."),
        list([
            "Skeleton — minimal, best for learning and greenfield projects",
            "Dawn — full-featured, best for production forks and pattern reference",
            "Horizon — newer Shopify reference theme (check Shopify GitHub for latest)",
        ]),
        note("Do not fork Dawn and submit it unchanged to the Theme Store. Shopify requires substantial differentiation for approval."),
    ]),
    page("shopify_cli_theme_dev", "theme dev — Local Development", [
        h2("Live Preview with Hot Reload"),
        p("shopify theme dev is the core daily workflow command. It uploads your local theme to a temporary development theme on your store, prints a preview URL, and watches files for changes. On save, CLI syncs the changed file and triggers a browser refresh."),
        code("bash", `cd my-theme\n\n# Start dev server\nshopify theme dev --store your-store.myshopify.com\n\n# Output example:\n# Preview: https://your-store.myshopify.com/?preview_theme_id=123456789\n# Shareable: https://your-store.myshopify.com/?preview_theme_id=123456789\n# (Ctrl+C to stop)`),
        h3("Useful Flags"),
        list([
            "--store — target .myshopify.com domain",
            "--theme THEME_ID — sync to an existing theme instead of creating a dev theme",
            "--only sections — sync only the sections/ folder (faster for large themes)",
            "--ignore config/settings_data.json — don't overwrite merchant editor changes",
            "--host 127.0.0.1 — local proxy configuration",
            "--port 9292 — custom local server port",
        ]),
        code("bash", `# Fast iteration: only sync Liquid partials\nshopify theme dev \\\n  --store your-store.myshopify.com \\\n  --only sections \\\n  --only snippets \\\n  --only layout`),
        steps([
            "Run theme dev in one terminal tab — leave it running all day",
            "Edit files in your editor — save triggers sync within 1-2 seconds",
            "Test on the preview URL — cart and checkout work with test payments",
            "Use browser DevTools for CSS/JS; use Liquid comments for template debugging",
        ]),
        tip("Add config/settings_data.json to .gitignore if multiple developers share a store — each dev's editor settings conflict otherwise."),
    ]),
    page("shopify_cli_theme_push", "theme push & pull", [
        h2("Deploying Theme Files to Shopify"),
        p("shopify theme push uploads local files to a remote theme. shopify theme pull downloads remote files to local. Use pull when a merchant edited the theme in Admin and you need to reconcile, or when taking over an existing store."),
        code("bash", `# List all themes on the store\nshopify theme list --store your-store.myshopify.com\n\n# Push to a NEW unpublished theme (safest for staging)\nshopify theme push \\\n  --store your-store.myshopify.com \\\n  --unpublished \\\n  --theme \"Staging v2\"\n\n# Push to an existing theme by ID\nshopify theme push \\\n  --store your-store.myshopify.com \\\n  --theme 123456789012\n\n# Push and publish live (DANGEROUS — prompts for confirmation)\nshopify theme push --store your-store.myshopify.com --publish\n\n# Pull remote theme to local\nshopify theme pull \\\n  --store your-store.myshopify.com \\\n  --theme 123456789012`),
        h3("Deployment Safety"),
        steps([
            "Always test on a development or unpublished theme first",
            "Run shopify theme check locally before every push",
            "Use --only and --ignore to push specific files during hotfixes",
            "Never push directly to live during business hours without a rollback plan",
            "Keep Git tags matching each production push for quick revert",
        ]),
        code("bash", `# Push only changed sections (hotfix)\nshopify theme push \\\n  --only sections/header.liquid \\\n  --theme LIVE_THEME_ID`),
        note("theme push overwrites remote files. It does not delete remote files that you deleted locally unless you use --nodelete false. Understand the flags before scripting deploys."),
    ]),
    page("shopify_cli_theme_check", "theme check — Linting", [
        h2("Static Analysis with Theme Check"),
        p("Theme Check scans your theme for Liquid syntax errors, deprecated tags, accessibility issues, and performance anti-patterns. It runs locally via CLI and in CI pipelines. Many Shopify Theme Store requirements map directly to Theme Check rules."),
        code("bash", `# Run all checks\nshopify theme check\n\n# List available checks\nshopify theme check --list\n\n# Auto-fix safe issues (deprecated filters, etc.)\nshopify theme check --auto-correct\n\n# Fail CI on errors only\nshopify theme check --fail-level error\n\n# Run specific check\nshopify theme check --include UndefinedObject`),
        h3("Common Violations"),
        list([
            "Missing {{ content_for_header }} in layout/theme.liquid",
            "Deprecated {% include %} — migrate to {% render %}",
            "Parser-blocking <script> in <head> without async/defer",
            "img tags missing width and height attributes",
            "Hardcoded /cart and /account URLs instead of routes",
            "Unused snippets, locales, and assign variables",
            "RemoteAsset — loading assets from non-Shopify CDNs",
        ]),
        p("Fix Theme Check errors before theme push. Warnings (performance suggestions) should be addressed for Theme Store submission but may be acceptable for custom client themes."),
        tip("Add a .theme-check.yml config to disable rules that do not apply to your project, but document why each disabled rule is intentional."),
    ]),
    page("shopify_cli_theme_package", "theme package & share", [
        h2("Distribution and Preview Links"),
        p("shopify theme package creates a .zip archive validated for Theme Store submission. shopify theme share generates a shareable preview link for client review without publishing."),
        code("bash", `# Create submission zip\nshopify theme package\n# Output: my-theme-1.0.0.zip in project root\n\n# Share preview link (expires)\nshopify theme share --store your-store.myshopify.com\n\n# Share a specific theme\nshopify theme share --theme 123456789012`),
        steps([
            "Run theme check — zero errors required for Theme Store",
            "Run theme package — CLI validates zip structure",
            "Submit zip via Partner Dashboard → Themes",
            "Use theme share for client approvals before publish",
        ]),
        note("Theme Store themes must include documentation, support contact, and meet accessibility and performance benchmarks beyond Theme Check."),
    ]),
    page("shopify_cli_github", "CLI + Git Workflow", [
        h2("Professional Theme Development Workflow"),
        p("Pair Git version control with Shopify CLI for team collaboration, code review, and safe deployments. Each environment (dev, staging, production) maps to a different Shopify theme on the same or different stores."),
        code("bash", `# ── Initial setup ──\ngit init\ngit add .\ngit commit -m "Initial theme scaffold"\ngit remote add origin git@github.com:your-org/your-theme.git\ngit push -u origin main\n\n# ── Daily development ──\ngit checkout -b feature/hero-section\nshopify theme dev --store dev-store.myshopify.com\n# ... edit sections/hero-banner.liquid ...\ngit add sections/hero-banner.liquid\ngit commit -m "Add hero banner section with video support"\ngit push origin feature/hero-section\n# Open PR for review\n\n# ── Deploy to staging ──\ngit checkout main\ngit pull\nshopify theme push \\\n  --store dev-store.myshopify.com \\\n  --unpublished \\\n  --theme \"Staging\"\n\n# ── Deploy to production (after QA sign-off) ──\nshopify theme push \\\n  --store production-store.myshopify.com \\\n  --theme PROD_THEME_ID\n\ngit tag v1.2.0\ngit push origin v1.2.0`),
        list([
            "main branch → production theme (protected, PR-only merges)",
            "develop branch → staging theme on dev store",
            "Feature branches → shopify theme dev ephemeral themes",
            "Tag releases matching shopify theme push deploys",
            "GitHub Actions can run theme check on every PR",
        ]),
        tip("Store THEME_IDs in environment variables or a deploy config — never hardcode production IDs in package.json scripts committed to public repos."),
    ]),
]);
