import { section, h2, h3, list, page, code, tryit, p, note, tip, steps } from "../builder";

const ext = "liquid";

export const liquidObjectsSection = section("Shopify Objects", [
    page("liquid_object_shop", "shop Object", [
        h2("The Global shop Object"),
        p("shop is a Liquid drop available on every page of your theme — homepage, product pages, cart, 404, and password page. It represents the merchant's store configuration from Shopify Admin. You never create or pass shop; Shopify injects it automatically."),
        code(ext, `{{ shop.name }}\n{{ shop.email }}\n{{ shop.currency }}\n{{ shop.domain }}\n{{ shop.permanent_domain }}\n{{ shop.description }}`, "Core shop properties"),
        list([
            "shop.name — store title shown in browser tabs and headers",
            "shop.email — customer-facing contact email",
            "shop.currency — ISO 4217 code (USD, GBP, EUR) for money filters",
            "shop.domain — current request domain (may differ per market)",
            "shop.permanent_domain — always your-store.myshopify.com",
            "shop.money_format — Liquid money format string for custom formatting",
            "shop.enabled_payment_types — array of accepted card brand icons",
        ]),
        p("Use shop.name in the footer copyright, shop.currency when building JavaScript price formatters, and shop.permanent_domain when you need a stable domain reference (webhooks, API callbacks) rather than a custom domain."),
        tryit("html", `<footer><p>&copy; 2026 Sturdee Store · USD</p></footer>`),
        tip("shop.address returns a structured address object — use shop.address.city, shop.address.country for localized footer content."),
    ]),
    page("liquid_object_product", "product Object", [
        h2("The product Drop on Product Pages"),
        p("On templates/product.json and product.liquid, Shopify provides a product object with every field from the product admin: title, description, variants, images, SEO, and metafields. On collection pages, each item in collection.products is also a product drop — but with fewer preloaded associations."),
        h3("Essential Properties"),
        list([
            "product.id — unique numeric ID (use in data attributes and JSON)",
            "product.title, product.handle — display name and URL slug",
            "product.description — HTML rich text from the admin editor",
            "product.price — lowest variant price in cents",
            "product.compare_at_price — MSRP when set on any variant",
            "product.available — true if at least one variant is purchasable",
            "product.url — canonical product URL path",
            "product.featured_image — primary image drop",
            "product.images — array of all product media",
            "product.variants — array of variant drops",
            "product.options — option names (Size, Color) without values",
            "product.tags, product.type, product.vendor — merchandising metadata",
            "product.metafields — custom namespace.key data",
        ]),
        code(ext, `<h1>{{ product.title }}</h1>\n<p class="vendor">{{ product.vendor }}</p>\n\n<div class="rte">{{ product.description }}</div>\n\n<select name="id" form="product-form">\n  {% for variant in product.variants %}\n    <option\n      value="{{ variant.id }}"\n      {% if variant == product.selected_or_first_available_variant %}selected{% endif %}\n      {% unless variant.available %}disabled{% endunless %}\n    >\n      {{ variant.title }} — {{ variant.price | money }}\n      {% unless variant.available %} (Sold out){% endunless %}\n    </option>\n  {% endfor %}\n</select>`, "Product page with variant selector"),
        steps([
            "product.selected_or_first_available_variant — URL ?variant= param or first in-stock variant",
            "variant.available — false when inventory is 0 and policy is 'deny'",
            "variant.id is required for add-to-cart — never use product.id in cart forms",
            "The rte class styles rich text HTML from product.description",
        ]),
        note("product.price returns the minimum variant price. On sale pages with wide price ranges, loop variants or use price_varies."),
    ]),
    page("liquid_object_collection", "collection Object", [
        h2("Collections and Product Listings"),
        p("A collection groups products for navigation and merchandising. On collection template pages, collection contains the current collection's metadata and a paginated subset of products. Smart collections are rule-based; custom collections are manually curated."),
        code(ext, `<header class="collection-header">\n  <h1>{{ collection.title }}</h1>\n  {% if collection.description != blank %}\n    <div class="rte">{{ collection.description }}</div>\n  {% endif %}\n  <p>{{ collection.all_products_count }} products</p>\n</header>\n\n{% paginate collection.products by 24 %}\n  <div class="collection-grid">\n    {% for product in collection.products %}\n      {% render 'product-card', product: product %}\n    {% endfor %}\n  </div>\n  {{ paginate | default_pagination }}\n{% endpaginate %}`, "Collection page with pagination"),
        list([
            "collection.handle — URL slug (/collections/programming)",
            "collection.products — products on current page (inside paginate)",
            "collection.all_products_count — total across all pages",
            "collection.products_count — same as all_products_count on collection pages",
            "collection.image — collection featured image for banners",
            "collection.sort_options — available sort orders for filter UI",
            "collection.filters — Storefront filtering API (OS 2.0)",
        ]),
        tip("Use collection.all_products_count for 'Showing X of Y' labels. collection.products.size is only the current page count inside paginate."),
    ]),
    page("liquid_object_cart", "cart Object", [
        h2("Cart State on Every Page"),
        p("cart reflects the current visitor's cart session. It updates on page reload after add-to-cart form submissions or AJAX cart API calls. cart is always present — even when empty (item_count = 0)."),
        code(ext, `{% if cart.item_count > 0 %}\n  <a href="{{ routes.cart_url }}" class="header__cart">\n    <span class="visually-hidden">Cart</span>\n    <span aria-hidden="true">🛒</span>\n    <span class="cart-count">{{ cart.item_count }}</span>\n    <span class="cart-total">{{ cart.total_price | money }}</span>\n  </a>\n{% else %}\n  <a href="{{ routes.cart_url }}" class="header__cart">Cart</a>\n{% endif %}`, "Header cart badge"),
        h3("Line Item Properties"),
        code(ext, `{% for item in cart.items %}\n  <div class="cart-line" data-key="{{ item.key }}">\n    <a href="{{ item.url }}">{{ item.product.title }}</a>\n    {% if item.variant.title != 'Default Title' %}\n      <p class="variant">{{ item.variant.title }}</p>\n    {% endif %}\n    <p>{{ item.quantity }} × {{ item.final_price | money }} = {{ item.line_price | money }}</p>\n    {% for property in item.properties %}\n      {% unless property.last == blank %}\n        <p>{{ property.first }}: {{ property.last }}</p>\n      {% endunless %}\n    {% endfor %}\n  </div>\n{% endfor %}`, "Cart drawer line items"),
        list([
            "item.key — unique line identifier for quantity updates",
            "item.final_price — price after line-level discounts",
            "item.line_price — final_price × quantity",
            "item.properties — custom fields (engraving, gift message)",
            "cart.total_price — subtotal before shipping/tax at checkout",
            "cart.currency — cart currency (multi-currency stores)",
        ]),
        note("Cart drawer UIs typically use /cart/add.js and /cart/change.js AJAX endpoints, then re-fetch sections via the Section Rendering API."),
    ]),
    page("liquid_object_customer", "customer Object", [
        h2("Logged-In Customer Session"),
        p("customer is nil for anonymous visitors. When logged in, it exposes profile data from the customer account. Use {% if customer %} to gate account-specific UI — never rely on hidden form fields for authentication."),
        code(ext, `{% if customer %}\n  <div class="account-nav">\n    <p>Welcome back, {{ customer.first_name }}!</p>\n    <a href="{{ routes.account_url }}">Account</a>\n    <a href="{{ routes.account_logout_url }}">Log out</a>\n  </div>\n{% else %}\n  <a href="{{ routes.account_login_url }}">Log in</a>\n  <a href="{{ routes.account_register_url }}">Create account</a>\n{% endif %}`, "Conditional account navigation"),
        list([
            "customer.email, customer.first_name, customer.last_name",
            "customer.orders — order history (account pages only)",
            "customer.addresses — saved shipping addresses",
            "customer.tags — segments for B2B or loyalty programs",
            "customer.accepts_marketing — email consent flag",
        ]),
        tip("For 'Reorder' buttons, loop customer.orders on the account page — each order has order.line_items with product references."),
    ]),
    page("liquid_object_routes", "routes Object", [
        h2("Canonical Store URLs"),
        p("routes provides locale- and market-aware URL paths. Hardcoding /cart or /account breaks when Shopify adds language prefixes (/en/cart) or custom routing. Always use routes for internal links."),
        list([
            "routes.root_url — homepage",
            "routes.cart_url, routes.cart_add_url, routes.cart_change_url",
            "routes.account_url, routes.account_login_url, routes.account_logout_url, routes.account_register_url",
            "routes.collections_url, routes.all_products_collection_url",
            "routes.search_url — /search with ?q= parameter",
            "routes.predictive_search_url — AJAX search endpoint",
        ]),
        code(ext, `<nav>\n  <a href="{{ routes.root_url }}">Home</a>\n  <a href="{{ routes.collections_url }}">Shop</a>\n  <a href="{{ routes.cart_url }}">Cart ({{ cart.item_count }})</a>\n  <a href="{{ routes.account_url }}">Account</a>\n</nav>\n\n<form action="{{ routes.search_url }}" method="get" role="search">\n  <input type="search" name="q" placeholder="Search courses…">\n</form>`, "Navigation with routes"),
        note("routes.cart_add_url is the form action target when not using {% form 'product' %} — prefer the form tag for CSRF protection."),
    ]),
    page("liquid_metafields", "Metafields in Liquid", [
        h2("Custom Data Beyond Standard Fields"),
        p("Metafields extend Shopify resources with merchant- or app-defined data: course duration, instructor bio, video URLs, sizing charts. They are organized by namespace and key, accessed as resource.metafields.namespace.key."),
        code(ext, `{% if product.metafields.custom.duration != blank %}\n  <p class="meta">Duration: {{ product.metafields.custom.duration }}</p>\n{% endif %}\n\n{% if product.metafields.custom.instructor != blank %}\n  <p>Taught by {{ product.metafields.custom.instructor }}</p>\n{% endif %}\n\n{% if product.metafields.custom.preview_video %}\n  <video controls poster="{{ product.featured_image | image_url: width: 800 }}">\n    <source src="{{ product.metafields.custom.preview_video | file_url }}">\n  </video>\n{% endif %}`, "Product metafields for a course store"),
        steps([
            "Define metafields in Admin → Settings → Custom data, or via an app",
            "Namespace 'custom' is the default for merchant-created fields",
            "Use | metafield_tag for Shopify's typed rendering (rich text, colors, references)",
            "Use | file_url for file_reference metafields (videos, PDFs)",
            "Always check != blank before rendering — undefined metafields return nil",
        ]),
        h3("List and JSON Metafields"),
        code(ext, `{% for module in product.metafields.custom.curriculum.value %}\n  <li>{{ module.title }} — {{ module.lessons }} lessons</li>\n{% endfor %}`, "Iterate a list metafield definition"),
        tip("Metafield definitions include a type (single_line_text, number_integer, list.metaobject_reference). Access .value on metaobject and list types for the parsed data."),
    ]),
]);
