import { section, h2, h3, list, page, code, tryit, p, note, tip, steps } from "../builder";

const ext = "liquid";

export const liquidTagsSection = section("Liquid Tags", [
    page("liquid_if", "Liquid If / Unless", [
        h2("Conditional Rendering in Themes"),
        p("Conditionals are the most-used Liquid tags in production themes. They let you show different HTML based on inventory, customer login state, cart contents, market, or any other store data — without duplicating entire template files."),
        h3("if / elsif / else"),
        p("The {% if %} tag evaluates a condition. If true, Liquid renders everything until {% elsif %}, {% else %}, or {% endif %}. You can chain multiple {% elsif %} branches for multi-way decisions."),
        code(ext, `{% if cart.item_count > 0 %}\n  <a href="{{ routes.cart_url }}" class="header__cart">\n  Cart ({{ cart.item_count }})\n  </a>\n{% else %}\n  <a href="{{ routes.cart_url }}" class="header__cart">Cart</a>\n{% endif %}`, "Cart link with item count"),
        p("cart.item_count is an integer updated on every page load. It reflects the total quantity of all line items (two of the same product counts as 2). Use cart.item_count > 0 rather than checking cart.items.size — they are equivalent but item_count is more readable."),
        h3("Product availability branching"),
        code(ext, `{% if product.compare_at_price > product.price %}\n  <span class="price price--sale">{{ product.price | money }}</span>\n  <s class="price price--compare">{{ product.compare_at_price | money }}</s>\n{% elsif product.available == false %}\n  <span class="badge badge--sold-out">Sold out</span>\n{% else %}\n  <span class="price">{{ product.price | money }}</span>\n{% endif %}`, "Sale, sold-out, and regular price states"),
        steps([
            "compare_at_price > price — Shopify shows a 'compare at' price when the merchant sets a higher MSRP",
            "product.available == false — all variants are out of stock or unavailable",
            "The final else branch handles the standard in-stock, non-sale case",
        ]),
        h3("unless — Inverted Conditions"),
        p("{% unless %} renders its body when the condition is false. It is equivalent to {% if condition == false %} but reads more naturally for guard clauses."),
        code(ext, `{% unless product.available %}\n  <p class="notice">This product is currently unavailable. Join our waitlist below.</p>\n  {% render 'back-in-stock-form', product: product %}\n{% endunless %}`, "Show waitlist only when sold out"),
        tryit("html", `<a href="/cart" class="header__cart">Cart (2)</a>`),
        note("Avoid deeply nested if blocks (more than 3 levels). Extract complex logic into {% liquid %} assign statements or snippets for maintainability."),
    ]),
    page("liquid_case", "Liquid Case", [
        h2("Multi-Way Branching with case"),
        p("When a single variable has many known values, {% case %} is cleaner than a long elsif chain. Liquid compares the variable to each {% when %} value and executes the first match."),
        code(ext, `{% case product.type %}\n  {% when 'Digital Course' %}\n    <span class="icon">📚</span>\n    <span>Instant digital access after purchase</span>\n  {% when 'Course Bundle' %}\n    <span class="icon">📦</span>\n    <span>Includes multiple courses</span>\n  {% when 'Coaching Session' %}\n    <span class="icon">🎯</span>\n    <span>Book a 1-on-1 session after checkout</span>\n  {% else %}\n    <span class="icon">🛒</span>\n    <span>Standard product</span>\n{% endcase %}`, "Product type messaging"),
        p("product.type is a free-text field merchants set in Admin. Document expected values in your theme's merchant documentation. For more structured data, prefer metafields over product.type."),
        tip("case only supports exact matches — not ranges or contains. Use if/elsif for complex conditions."),
    ]),
    page("liquid_for", "Liquid For Loops", [
        h2("Iterating Collections and Arrays"),
        p("The {% for %} tag loops over arrays: collection.products, cart.items, product.variants, linklists, and arrays you create with assign. Each iteration exposes the current item and a forloop helper object."),
        code(ext, `{% for product in collection.products limit: 8 %}\n  <article class="product-card">\n    <a href="{{ product.url }}">\n      <img\n        src="{{ product.featured_image | image_url: width: 400 }}"\n        alt="{{ product.title | escape }}"\n        width="400"\n        height="400"\n        loading="lazy"\n      >\n      <h3>{{ product.title }}</h3>\n      <p>{{ product.price | money }}</p>\n    </a>\n  </article>\n{% else %}\n  <p>No products found in this collection.</p>\n{% endfor %}`, "Product grid with limit and empty state"),
        p("The limit: 8 parameter caps iterations — essential for homepage featured grids. The {% else %} branch inside for runs when the array is empty, letting you show a friendly message instead of a blank section."),
        h3("The forloop Object"),
        p("Every for loop provides forloop with metadata about the iteration. Use it for zebra striping, first/last item styling, and progress indicators."),
        list([
            "forloop.index — 1-based position (1, 2, 3…)",
            "forloop.index0 — 0-based position (0, 1, 2…)",
            "forloop.first — true on the first iteration",
            "forloop.last — true on the final iteration",
            "forloop.length — total number of items in the array",
            "forloop.rindex — reverse index (countdown from end)",
        ]),
        code(ext, `{% for item in cart.items %}\n  <tr class="cart-item{% if forloop.first %} cart-item--first{% endif %}{% if forloop.last %} cart-item--last{% endif %}">\n    <td>{{ forloop.index }}</td>\n    <td>{{ item.product.title }}</td>\n    <td>{{ item.line_price | money }}</td>\n  </tr>\n{% endfor %}`, "Cart table with row styling"),
        h3("Loop Modifiers"),
        list([
            "limit: N — stop after N items",
            "offset: N — skip the first N items (pagination alternative)",
            "reversed — iterate from last to first",
        ]),
        tryit("html", `<article class="product-card"><a href="#"><h3>Full-Stack Web Development</h3><p>$1,899.00</p></a></article>`),
        note("Nested loops (collection × variants) multiply render cost. On large catalogs, paginate collections and avoid rendering every variant in listing pages."),
    ]),
    page("liquid_tablerow", "Liquid tablerow", [
        h2("Grid Layouts with tablerow"),
        p("{% tablerow %} wraps items in HTML table rows, breaking into a new row every cols: N items. Before CSS Grid was universal, this was the standard Shopify pattern for product grids. It still appears in legacy themes and email templates."),
        code(ext, `<table class="product-grid">\n  {% tablerow product in collection.products cols: 4 %}\n    <td class="product-grid__cell">\n      <a href="{{ product.url }}">{{ product.title }}</a>\n    </td>\n  {% endtablerow %}\n</table>`, "4-column product table"),
        p("Modern themes should prefer CSS Grid or Flexbox with a standard {% for %} loop. tablerow outputs <tr> and <td> elements — only use it when you genuinely need table semantics or maintain legacy markup."),
        tip("For new Online Store 2.0 sections, use display: grid in CSS with {% for product in collection.products %} — it is more flexible and accessible."),
    ]),
    page("liquid_render", "render & include", [
        h2("Reusable Snippets with render"),
        p("Snippets are partial Liquid files in snippets/. The {% render %} tag inserts a snippet with an isolated variable scope — the snippet only sees variables you pass explicitly (plus global objects like shop and routes)."),
        code(ext, `{%- render 'product-card',\n    product: product,\n    show_vendor: true,\n    image_width: 500\n-%}`, "Render with named parameters"),
        steps([
            "Create snippets/product-card.liquid with the card markup",
            "Pass product and optional flags as parameters",
            "Inside the snippet, access product.title, show_vendor, image_width directly",
            "Variables from the parent template are NOT visible unless passed",
        ]),
        h3("Why render Replaced include"),
        p("{% include 'snippet' %} is deprecated. include shared the entire parent scope, causing naming collisions and making snippets harder to reason about. Theme Check flags every include — migrate to render."),
        code(ext, `{%- comment -%} snippets/icon-cart.liquid {%- endcomment -%}\n<svg aria-hidden="true" class="icon icon-cart" width="20" height="20">...</svg>`, "Icon snippet with no parameters"),
        note("Snippet filenames use kebab-case without the .liquid extension in the render tag: {% render 'product-card' %} maps to snippets/product-card.liquid."),
    ]),
    page("liquid_paginate", "Liquid Paginate", [
        h2("Splitting Large Collections Across Pages"),
        p("Shopify limits how many items you can efficiently loop per request. The {% paginate %} tag wraps a for loop and splits results into pages. Shopify provides a paginate object with current page, page size, and total pages."),
        code(ext, `{% paginate collection.products by 12 %}\n  <div class="collection-grid">\n    {% for product in collection.products %}\n      {% render 'product-card', product: product %}\n    {% endfor %}\n  </div>\n\n  {% if paginate.pages > 1 %}\n    <nav class="pagination" aria-label="Pagination">\n      {{ paginate | default_pagination }}\n    </nav>\n  {% endif %}\n{% endpaginate %}`, "12 products per page with navigation"),
        p("The by 12 parameter sets page size. collection.products inside the paginate block only contains the current page's products — not the entire catalog. Use collection.all_products_count for total count display outside the loop."),
        list([
            "paginate.current_page — active page number",
            "paginate.pages — total page count",
            "paginate.next.url / paginate.previous.url — navigation links",
            "default_pagination filter — renders Previous/Next and page numbers",
        ]),
        tip("For AJAX 'Load more' UX, use the Section Rendering API or fetch ?page=2 URLs — paginate is the server-side foundation."),
    ]),
    page("liquid_forms", "Liquid Forms", [
        h2("Shopify Form Tags"),
        p("Never hand-write <form action=\"/cart/add\"> without Shopify's form tag. The {% form %} tag generates correct action URLs, CSRF tokens, and hidden fields required for secure cart and customer operations."),
        h3("Product Form — Add to Cart"),
        code(ext, `{% form 'product', product, id: 'product-form', class: 'product-form' %}\n  <input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}">\n  <button type="submit" name="add" class="btn">\n    Add to cart\n  </button>\n{% endform %}`, "Minimal add-to-cart form"),
        steps([
            "form 'product' tells Shopify this submits to /cart/add",
            "name=\"id\" must be the variant ID (not product ID) — critical for multi-variant products",
            "name=\"add\" on the submit button triggers add-to-cart (not checkout)",
            "The id: parameter sets the HTML id attribute for JavaScript hooks",
        ]),
        h3("Cart Update Form"),
        code(ext, `{% form 'cart', cart %}\n  <table class="cart-table">\n    {% for item in cart.items %}\n      <tr>\n        <td>{{ item.product.title }}</td>\n        <td>\n          <input type="number" name="updates[{{ item.key }}]" value="{{ item.quantity }}" min="0">\n        </td>\n        <td>{{ item.line_price | money }}</td>\n      </tr>\n    {% endfor %}\n  </table>\n  <button type="submit" name="update">Update cart</button>\n  <button type="submit" name="checkout">Checkout</button>\n{% endform %}`, "Quantity updates and checkout"),
        p("item.key is a unique line-item identifier (variant + properties). Use updates[KEY] naming for quantity changes. Setting quantity to 0 removes the line item."),
        note("For dynamic cart drawers, use the Cart AJAX API (/cart/add.js, /cart/change.js) in JavaScript instead of full page form posts."),
    ]),
]);
