import type { BlogTopic } from "./types";

type Specialized = Pick<BlogTopic, "headings" | "whyItMatters" | "deepDive" | "focusKeyword" | "seoTitle">;

/** Per-URL specialized SEO content — unique headings and paragraphs for every blog slug. */
export const SPECIALIZED_BY_SLUG: Record<string, Specialized> = {
    "what-is-html-semantic-markup-guide": {
        focusKeyword: "HTML semantic markup",
        headings: { intro: "What Is HTML Semantic Markup?" },
        whyItMatters: "Google and screen readers parse semantic tags to understand page structure — directly affecting rankings and accessibility scores.",
        deepDive: "Replacing div soup with <article>, <nav>, and <main> gives crawlers explicit signals about which content is navigation versus primary editorial text.",
    },
    "html-forms-accessibility-best-practices": {
        focusKeyword: "accessible HTML forms",
        headings: { intro: "Building Accessible HTML Forms" },
        whyItMatters: "Inaccessible forms increase bounce rates and exclude users — WCAG violations can also create legal risk for commercial sites.",
        deepDive: "Programmatic labels, visible error text, and logical tab order are the three fixes that resolve most form accessibility audit failures.",
    },
    "html-seo-meta-tags-guide": {
        focusKeyword: "HTML meta tags SEO",
        headings: { intro: "HTML Meta Tags That Affect Google Rankings" },
        whyItMatters: "Title and description meta tags are your ad copy in search results — a 5% CTR lift from better meta can outperform a ranking jump.",
        deepDive: "Each URL needs a unique title and description; duplicate meta across pages is a common reason Google rewrites your snippets.",
    },
    "responsive-html-mobile-first": {
        focusKeyword: "responsive HTML",
        headings: { intro: "Mobile-First HTML Structure" },
        whyItMatters: "Google indexes mobile-first; if your HTML structure breaks on small screens, you lose mobile rankings regardless of CSS quality.",
        deepDive: "Viewport meta, logical heading order, and responsive images in HTML ensure content is parseable before stylesheets load.",
    },
    "html-tables-data-guide": {
        focusKeyword: "HTML data tables",
        headings: { intro: "When and How to Use HTML Tables" },
        whyItMatters: "Misused layout tables harm accessibility; properly marked data tables help users and search engines understand tabular relationships.",
        deepDive: "Use <th scope='col'> and <caption> so assistive technology announces headers with each cell value.",
    },
    "html-aria-accessibility-guide": {
        focusKeyword: "ARIA accessibility",
        headings: { intro: "ARIA Roles and Labels in HTML" },
        whyItMatters: "ARIA fills gaps when native HTML cannot express widget semantics — critical for SPAs and custom components.",
        deepDive: "Rule one: use native HTML first. Add aria-label or role only when no semantic element exists for your UI pattern.",
    },
    "css-flexbox-complete-guide": {
        focusKeyword: "CSS Flexbox",
        headings: { intro: "CSS Flexbox Layout Explained" },
        whyItMatters: "Flexbox is the default tool for component-level layout in modern CSS — navbars, toolbars, and card rows all depend on it.",
        deepDive: "Master justify-content and align-items on the parent, then flex-grow on children — that covers 90% of real Flexbox use cases.",
    },
    "css-grid-layout-tutorial": {
        focusKeyword: "CSS Grid",
        headings: { intro: "CSS Grid for Page Layouts" },
        whyItMatters: "Grid handles two-dimensional layouts that Flexbox cannot — dashboards, galleries, and full-page templates are faster with Grid.",
        deepDive: "auto-fit and minmax() create responsive columns without a single media query — a pattern every responsive site should use.",
    },
    "css-responsive-design-breakpoints": {
        focusKeyword: "CSS responsive breakpoints",
        headings: { intro: "Mobile-First CSS Breakpoints" },
        whyItMatters: "Breakpoints should emerge from content breaking, not from device lists — this prevents fragile layouts on new screen sizes.",
        deepDive: "Start with single-column base styles, then add min-width media queries only when content genuinely needs more horizontal space.",
    },
    "css-variables-custom-properties": {
        focusKeyword: "CSS custom properties",
        headings: { intro: "CSS Variables for Theming" },
        whyItMatters: "Custom properties enable runtime theme switching and consistent design tokens — required for dark mode and white-label products.",
        deepDive: "Define tokens on :root, override in [data-theme='dark'], and reference with var(--token) everywhere instead of hard-coded hex values.",
    },
    "tailwind-css-vs-traditional-css": {
        focusKeyword: "Tailwind CSS vs CSS",
        headings: { intro: "Tailwind vs Traditional CSS" },
        whyItMatters: "Teams choose Tailwind for speed; traditional CSS for maximum control. Knowing both makes you adaptable across codebases.",
        deepDive: "Learn box model, cascade, and specificity in plain CSS first — then Tailwind utilities map directly to those concepts.",
    },
    "css-animations-transitions-guide": {
        focusKeyword: "CSS animations",
        headings: { intro: "CSS Transitions and Keyframe Animations" },
        whyItMatters: "Motion communicates state changes — but only transform and opacity animations stay on the GPU compositor thread for 60fps performance.",
        deepDive: "Use transition for hover/focus state changes; reserve @keyframes for loaders and multi-step entrance effects.",
    },
    "css-specificity-explained": {
        focusKeyword: "CSS specificity",
        headings: { intro: "How CSS Specificity Works" },
        whyItMatters: "Specificity wars cause !important sprawl and unmaintainable stylesheets — understanding the cascade prevents months of CSS debt.",
        deepDive: "Inline > ID > class > element. When styles conflict, count selectors — don't escalate with !important unless documenting why.",
    },
    "dark-mode-css-implementation": {
        focusKeyword: "dark mode CSS",
        headings: { intro: "Implementing Dark Mode in CSS" },
        whyItMatters: "Dark mode reduces eye strain and is a user expectation on developer tools and content sites — implement it with CSS, not heavy JS.",
        deepDive: "Combine prefers-color-scheme for auto mode with a data-theme toggle that swaps CSS variable values on the root element.",
    },
    "javascript-closures-explained": {
        focusKeyword: "JavaScript closures",
        headings: { intro: "JavaScript Closures — Plain English" },
        whyItMatters: "Closures appear in React hooks, debounce utilities, and module patterns — interviewers and production code both assume you understand them.",
        deepDive: "An inner function that references outer variables keeps that outer scope alive — that's the closure developers debug daily.",
    },
    "javascript-async-await-guide": {
        focusKeyword: "JavaScript async await",
        headings: { intro: "async/await in JavaScript" },
        whyItMatters: "Every API call, database query, and file read in modern JavaScript is asynchronous — async/await is how you manage that complexity.",
        deepDive: "await only works inside async functions; wrap await in try/catch because rejected Promises become catchable errors.",
    },
    "javascript-es6-features-guide": {
        focusKeyword: "JavaScript ES6",
        headings: { intro: "ES6+ Features You Use Every Day" },
        whyItMatters: "Arrow functions, destructuring, and modules are not optional syntax — they're in every npm package and framework codebase.",
        deepDive: "const/let block scoping prevents hoisting bugs; destructuring simplifies API response handling in a single line.",
    },
    "javascript-array-methods-map-filter": {
        focusKeyword: "JavaScript map filter reduce",
        headings: { intro: "map, filter, and reduce in JavaScript" },
        whyItMatters: "Functional array methods replace error-prone for-loops and are the idiomatic way to transform API data in React and Node.",
        deepDive: "Chain map → filter → reduce to parse, clean, and aggregate collections in one readable pipeline.",
    },
    "javascript-dom-manipulation-guide": {
        focusKeyword: "JavaScript DOM manipulation",
        headings: { intro: "Manipulating the DOM with JavaScript" },
        whyItMatters: "Before React, you must understand how the DOM works — querySelector, events, and classList are what frameworks abstract.",
        deepDive: "Batch DOM reads and writes to avoid layout thrashing; use documentFragment when inserting many nodes at once.",
    },
    "javascript-fetch-api-tutorial": {
        focusKeyword: "JavaScript fetch API",
        headings: { intro: "Using fetch() for HTTP Requests" },
        whyItMatters: "fetch is the browser-native way to load JSON, submit forms, and integrate third-party APIs without extra libraries.",
        deepDive: "Always check res.ok — fetch resolves on HTTP 404; only network failures reject the Promise.",
    },
    "javascript-error-handling-best-practices": {
        focusKeyword: "JavaScript error handling",
        headings: { intro: "Error Handling Patterns in JavaScript" },
        whyItMatters: "Unhandled Promise rejections crash Node servers and leave users staring at spinners — proper errors separate hobby projects from production apps.",
        deepDive: "Use custom Error subclasses for domain failures; log stack traces server-side and show human messages client-side.",
    },
    "typescript-vs-javascript-guide": {
        focusKeyword: "TypeScript vs JavaScript",
        headings: { intro: "TypeScript vs JavaScript in 2026" },
        whyItMatters: "TypeScript catches an entire class of bugs before runtime and powers IDE autocomplete — most hiring frontend roles expect it.",
        deepDive: "TypeScript is a compile step, not a new runtime — you can adopt it file-by-file in existing JavaScript projects.",
    },
    "react-hooks-explained-beginners": {
        focusKeyword: "React hooks",
        headings: { intro: "useState and useEffect Explained" },
        whyItMatters: "Hooks are how modern React components manage state and side effects — class components are legacy in new codebases.",
        deepDive: "The dependency array in useEffect controls when effects re-run; omitting it causes infinite loops, over-specifying causes stale bugs.",
    },
    "nodejs-beginners-guide": {
        focusKeyword: "Node.js beginners",
        headings: { intro: "Getting Started with Node.js" },
        whyItMatters: "Node lets JavaScript developers build APIs, CLIs, and build tools — one language across frontend and backend reduces context switching.",
        deepDive: "Start with npm init, built-in fs and path modules, then graduate to Express or Next.js API routes for HTTP.",
    },
    "nextjs-app-router-guide": {
        focusKeyword: "Next.js App Router",
        headings: { intro: "Next.js App Router in Practice" },
        whyItMatters: "App Router enables Server Components, streaming, and built-in SEO metadata — it's the default for new Next.js projects in 2026.",
        deepDive: "Server Components run on the server only; add 'use client' only when you need hooks, events, or browser APIs.",
    },
    "python-list-comprehensions-guide": {
        focusKeyword: "Python list comprehensions",
        headings: { intro: "Python List Comprehension Syntax" },
        whyItMatters: "Comprehensions are idiomatic Python — they're faster to read and write than manual loops in data processing scripts.",
        deepDive: "[expr for x in iterable if condition] replaces three-line loops and is the pattern pandas-adjacent code uses constantly.",
    },
    "python-virtual-environments-guide": {
        focusKeyword: "Python virtual environment",
        headings: { intro: "Python venv and pip Workflow" },
        whyItMatters: "Without venv, global package installs cause version conflicts that are painful to debug across team machines.",
        deepDive: "One venv per project, requirements.txt committed to git, never pip install globally for application dependencies.",
    },
    "python-django-vs-flask": {
        focusKeyword: "Django vs Flask",
        headings: { intro: "Choosing Django or Flask" },
        whyItMatters: "Framework choice shapes project velocity — Django ships admin and ORM; Flask stays minimal for APIs and microservices.",
        deepDive: "Pick Django for content sites and CRUD apps; Flask when you want explicit control over every dependency.",
    },
    "python-data-types-explained": {
        focusKeyword: "Python data types",
        headings: { intro: "Python Built-in Types" },
        whyItMatters: "Confusing list mutability with tuple immutability causes subtle bugs — types are the foundation of every Python script.",
        deepDive: "Lists are ordered and mutable; tuples are hashable records; dicts map keys to values in O(1) average lookup.",
    },
    "python-automation-scripts-guide": {
        focusKeyword: "Python automation",
        headings: { intro: "Automating Tasks with Python" },
        whyItMatters: "Python automation saves hours on file renaming, CSV processing, and API polling — high ROI for non-developers too.",
        deepDive: "Combine pathlib for files, csv for spreadsheets, and requests for HTTP — three modules cover most office automation.",
    },
    "learn-python-web-development": {
        focusKeyword: "Python web development",
        headings: { intro: "Python Web Development Roadmap" },
        whyItMatters: "Python backends power Instagram-scale apps and tiny startups alike — Django and FastAPI dominate the hiring market.",
        deepDive: "Learn core Python → pick a framework → add PostgreSQL → deploy with gunicorn or ASGI — skip frameworks until syntax is solid.",
    },
    "shopify-liquid-basics-guide": {
        focusKeyword: "Shopify Liquid",
        headings: { intro: "Shopify Liquid Template Language" },
        whyItMatters: "Liquid is the gateway to Shopify theme development — a niche skill with strong freelance demand and less competition than React.",
        deepDive: "Output tags {{ }} print data; logic tags {% %} control flow; objects like product and collection hold storefront data.",
    },
    "shopify-theme-customization-guide": {
        focusKeyword: "Shopify theme customization",
        headings: { intro: "Customizing Shopify OS 2.0 Themes" },
        whyItMatters: "Merchants pay premium rates for custom sections and performance fixes — theme customization is a billable Shopify skill.",
        deepDive: "JSON templates + section schema let merchants rearrange pages without code deploys — build sections, not one-off templates.",
    },
    "shopify-cli-setup-guide": {
        focusKeyword: "Shopify CLI setup",
        headings: { intro: "Installing and Using Shopify CLI" },
        whyItMatters: "CLI hot reload cuts theme development time in half versus manually uploading zip files to the admin.",
        deepDive: "shopify theme dev tunnels your local files to a development theme — edits appear instantly on a preview URL.",
    },
    "shopify-sections-blocks-explained": {
        focusKeyword: "Shopify sections blocks",
        headings: { intro: "Sections and Blocks Architecture" },
        whyItMatters: "Blocks make sections reusable and merchant-configurable — the OS 2.0 pattern every modern Shopify theme follows.",
        deepDive: "Schema presets define what merchants see in the editor; blocks loop with {% for block in section.blocks %}.",
    },
    "shopify-liquid-filters-objects": {
        focusKeyword: "Liquid filters and objects",
        headings: { intro: "Liquid Objects and Filters Reference" },
        whyItMatters: "Filters transform output at render time — money formatting, image URLs, and truncation all happen through the filter pipe.",
        deepDive: "{{ product.price | money }} and {{ image | img_url: '600x' }} are the two filters you'll use on every product card.",
    },
    "how-to-become-web-developer-2026": {
        focusKeyword: "become web developer 2026",
        headings: { intro: "Your Web Developer Roadmap for 2026" },
        whyItMatters: "Web development hiring remains strong — but employers expect portfolios and fundamentals, not tutorial completion certificates alone.",
        deepDive: "Six months of HTML → CSS → JavaScript → one framework → deployed projects beats two years of random video watching.",
    },
    "coding-portfolio-projects-beginners": {
        focusKeyword: "coding portfolio projects",
        headings: { intro: "Portfolio Projects That Impress Recruiters" },
        whyItMatters: "Your GitHub is your resume for junior roles — three polished deployed projects outperform twenty tutorial clones.",
        deepDive: "Each project needs a README with screenshots, live demo link, and two paragraphs explaining technical decisions you made.",
    },
    "technical-interview-prep-guide": {
        focusKeyword: "technical interview prep",
        headings: { intro: "Developer Interview Preparation" },
        whyItMatters: "Interviews test communication as much as code — explaining your approach aloud is what separates pass from fail.",
        deepDive: "Balance LeetCode medium practice with one system design outline and three STAR behavioral stories from real projects.",
    },
    "github-for-beginners-guide": {
        focusKeyword: "GitHub for beginners",
        headings: { intro: "Git and GitHub Essentials" },
        whyItMatters: "No professional team works without version control — GitHub is where your portfolio lives and where collaboration happens.",
        deepDive: "Commit early, push daily, write imperative commit messages ('Add login form' not 'fixed stuff').",
    },
    "remote-developer-jobs-guide": {
        focusKeyword: "remote developer jobs",
        headings: { intro: "Landing Remote Developer Roles" },
        whyItMatters: "Remote expands your job market globally — but you're competing with developers worldwide, so portfolio quality matters more.",
        deepDive: "Async communication skills and documented READMEs signal remote-readiness better than claiming 'self-starter' on a resume.",
    },
    "learning-to-code-while-working": {
        focusKeyword: "learn to code while working",
        headings: { intro: "Studying Code With a Full-Time Job" },
        whyItMatters: "Most career switchers learn while employed — sustainable 1-hour daily habits beat unsustainable weekend cramming.",
        deepDive: "Block the same hour daily, one Sturdee lesson per session, weekends only for portfolio builds — protect the streak.",
    },
    "sql-joins-explained-beginners": {
        focusKeyword: "SQL JOINs explained",
        headings: { intro: "SQL JOIN Types Visualized" },
        whyItMatters: "JOINs are the #1 SQL interview topic and appear in every analytics query joining users to orders or posts to comments.",
        deepDive: "INNER JOIN returns matches only; LEFT JOIN keeps all left rows with NULLs where right side has no match.",
    },
    "postgresql-vs-mysql-guide": {
        focusKeyword: "PostgreSQL vs MySQL",
        headings: { intro: "PostgreSQL or MySQL for Your App?" },
        whyItMatters: "Database choice affects hosting, JSON support, and hiring — Postgres leads in modern startups; MySQL in legacy LAMP stacks.",
        deepDive: "Learn standard SQL first on either engine — 90% of queries transfer; optimize for your host's managed offering.",
    },
    "rest-api-design-basics": {
        focusKeyword: "REST API design",
        headings: { intro: "RESTful API Design Principles" },
        whyItMatters: "Every frontend talks to REST APIs — designing predictable endpoints reduces integration bugs and documentation burden.",
        deepDive: "Use nouns for resources (/users not /getUsers), HTTP verbs for actions, and consistent JSON error shapes with status codes.",
    },
    "git-branching-workflow-guide": {
        focusKeyword: "Git branching workflow",
        headings: { intro: "Git Branching for Teams" },
        whyItMatters: "Branching discipline prevents main from breaking — feature branches and pull requests are standard on every professional team.",
        deepDive: "Branch from latest main, keep branches short-lived, open PR when ready for review — not when 'perfect'.",
    },
    "docker-for-developers-beginners": {
        focusKeyword: "Docker for developers",
        headings: { intro: "Docker Containers Explained" },
        whyItMatters: "Docker eliminates environment drift — the classic 'works on my machine' problem that wastes onboarding days.",
        deepDive: "Image is the recipe; container is the running instance; docker-compose wires app + database for local dev.",
    },
    "api-authentication-jwt-guide": {
        focusKeyword: "JWT authentication",
        headings: { intro: "JWT API Authentication" },
        whyItMatters: "SPAs and mobile apps authenticate with tokens — JWT is the most common format you'll implement or debug.",
        deepDive: "Sign tokens server-side, verify on every protected route, use short expiry plus refresh tokens for long sessions.",
    },
    "vscode-extensions-web-developers": {
        focusKeyword: "VS Code extensions",
        headings: { intro: "Essential VS Code Extensions" },
        whyItMatters: "The right extensions catch bugs at write-time — ESLint and Prettier alone prevent hours of code review nitpicks.",
        deepDive: "Configure format-on-save with Prettier and let ESLint enforce project rules — consistency matters more than extension count.",
    },
    "web-performance-core-web-vitals": {
        focusKeyword: "Core Web Vitals",
        headings: { intro: "Core Web Vitals for Developers" },
        whyItMatters: "LCP, INP, and CLS are Google ranking signals — slow sites lose both SEO position and conversion rate.",
        deepDive: "Optimize LCP with priority images and server response; fix CLS by reserving space for images and ads before they load.",
    },
    "seo-for-developers-guide": {
        focusKeyword: "SEO for developers",
        headings: { intro: "Technical SEO Checklist for Devs" },
        whyItMatters: "Developers ship the sitemap, canonical tags, and page speed that marketing cannot fix after launch.",
        deepDive: "Unique URLs, valid metadata per page, structured data, and fast TTFB — that's the technical SEO foundation.",
    },
    "json-explained-developers": {
        focusKeyword: "JSON explained",
        headings: { intro: "JSON for API Developers" },
        whyItMatters: "JSON is the lingua franca of REST APIs — every fetch call parses JSON; every backend serializes it.",
        deepDive: "Double quotes on keys, no trailing commas, JSON.parse in try/catch — invalid JSON crashes silent failures into visible errors.",
    },
    "blockchain-smart-contracts-beginners": {
        focusKeyword: "smart contracts beginners",
        headings: { intro: "Smart Contracts on Ethereum" },
        whyItMatters: "Smart contracts automate trustless agreements — niche but high-paying for developers who understand Solidity security.",
        deepDive: "Contracts run on-chain immutably — bugs are expensive; test on testnets and audit before mainnet deployment.",
    },
    "rust-programming-why-learn": {
        focusKeyword: "learn Rust programming",
        headings: { intro: "Why Developers Learn Rust" },
        whyItMatters: "Rust offers C++ performance without garbage collection pauses — growing in infrastructure, WASM, and blockchain tooling.",
        deepDive: "The borrow checker is hard at first but eliminates entire classes of memory bugs that plague C and C++ codebases.",
    },
};
