import type { BlogTopic } from "../types";

const D = "2026-01-25";
const D2 = "2026-02-10";
const D3 = "2026-02-22";
const D4 = "2026-03-12";

export const CAREER_TOPICS: BlogTopic[] = [
    {
        slug: "how-to-become-web-developer-2026",
        title: "How to Become a Web Developer in 2026 — Step-by-Step",
        description: "Realistic path to become a web developer: skills, portfolio, timeline, and free resources including Sturdee tutorials.",
        keywords: ["become web developer", "web developer 2026", "how to become developer"],
        category: "Career",
        readTime: "12 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/html",
        intro: "Web development remains one of the most accessible high-income skills. You don't need a degree — you need consistent practice, projects, and proof you can ship.",
        steps: ["Months 1–2: HTML, CSS, JavaScript on Sturdee", "Month 3: React or Next.js project", "Month 4: Backend + database", "Month 5: Portfolio + GitHub", "Month 6: Apply and interview"],
        practice: "Start today with /tutorials/html — free, interactive, no signup required for lessons.",
        faq: [{ question: "How long to get hired?", answer: "6–12 months of focused part-time study is typical for career switchers." }],
    },
    {
        slug: "coding-portfolio-projects-beginners",
        title: "10 Coding Portfolio Projects for Beginners That Get Hired",
        description: "Portfolio project ideas for junior developers: todo app, weather API, blog, e-commerce mock, and what recruiters look for.",
        keywords: ["coding portfolio projects", "beginner developer portfolio", "web developer projects"],
        category: "Career",
        readTime: "10 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/javascript",
        intro: "Recruiters spend 30 seconds on portfolios. Show 3–5 polished projects with README, live demo, and clean code — not 20 half-finished tutorials.",
        concepts: ["Todo app — CRUD + localStorage", "Weather app — fetch API", "Landing page — responsive CSS", "Blog with Next.js — SEO + CMS", "Shopify or e-commerce mock"],
        practice: "Build each project using skills from Sturdee tutorials. Link projects from your GitHub README.",
        faq: [{ question: "How many projects?", answer: "3–5 strong projects beat 10 mediocre ones." }],
    },
    {
        slug: "technical-interview-prep-guide",
        title: "Technical Interview Prep — Coding, System Design & Behavior",
        description: "Prepare for developer interviews: LeetCode strategy, system design basics, STAR behavioral answers, and take-home projects.",
        keywords: ["technical interview prep", "coding interview", "developer interview"],
        category: "Career",
        readTime: "11 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/javascript",
        intro: "Interviews test algorithms, system thinking, and communication. Prepare all three — not just LeetCode grinding.",
        concepts: ["Easy/medium LeetCode patterns", "Explain your thought process aloud", "System design for senior roles", "STAR method for behavioral", "Take-home: ship clean README"],
        practice: "Strengthen fundamentals with Sturdee algorithms and data structure lessons.",
        faq: [{ question: "How many LeetCode problems?", answer: "50–100 well-understood problems beat 500 memorized solutions." }],
    },
    {
        slug: "github-for-beginners-guide",
        title: "GitHub for Beginners — Repos, Commits, Pull Requests",
        description: "Learn Git and GitHub: init, commit, push, branches, pull requests, and open source contribution basics.",
        keywords: ["github for beginners", "learn git", "git tutorial"],
        category: "Career",
        readTime: "9 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/git",
        intro: "Git tracks code changes. GitHub hosts repositories and enables collaboration. Every developer job expects Git fluency.",
        steps: ["git init and first commit", "Create GitHub repo and push", "Branch for features", "Open pull request", "Write meaningful commit messages"],
        practice: "Follow the Git tutorial on Sturdee and push every tutorial exercise to GitHub.",
        faq: [{ question: "Git vs GitHub?", answer: "Git is version control software. GitHub is a hosting platform for Git repos." }],
    },
    {
        slug: "remote-developer-jobs-guide",
        title: "Remote Developer Jobs — How to Find and Land Remote Work",
        description: "Find remote software jobs: job boards, async communication, time zones, and portfolio tips for remote-first companies.",
        keywords: ["remote developer jobs", "remote programming jobs", "work from home developer"],
        category: "Career",
        readTime: "8 min read",
        publishedAt: D,
        tutorialPath: "/tutorials",
        intro: "Remote development jobs exploded post-2020. Companies hire globally — but competition is global too. Strong GitHub and communication skills matter more.",
        concepts: ["Remote job boards: We Work Remotely, RemoteOK", "Async written communication", "Portfolio with deployed demos", "Time zone overlap expectations", "Contract vs full-time remote"],
        practice: "Build deployable projects from Sturdee tutorials to show remote-ready self-direction.",
        faq: [{ question: "Do remote jobs pay less?", answer: "Varies. Many US companies pay well globally; some adjust for location." }],
    },
    {
        slug: "learning-to-code-while-working",
        title: "Learning to Code While Working Full-Time — Realistic Schedule",
        description: "Study plan for learning programming with a day job: 1-hour daily habit, weekends, burnout avoidance, and milestones.",
        keywords: ["learn to code while working", "part time coding", "learn programming schedule"],
        category: "Career",
        readTime: "7 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials",
        intro: "Most self-taught developers learned while employed elsewhere. Consistency beats intensity — 1 focused hour daily compounds faster than weekend marathons.",
        concepts: ["1 hour before or after work", "One tutorial lesson per day on Sturdee", "Weekends for projects only", "Track streaks in a journal", "Rest days prevent burnout"],
        practice: "Set a daily alarm for one Sturdee lesson — lessons are 15–20 minutes each.",
        faq: [{ question: "How many hours per week?", answer: "7–10 hours weekly is sustainable and effective for most working adults." }],
    },
];

export const BACKEND_TOPICS: BlogTopic[] = [
    {
        slug: "sql-joins-explained-beginners",
        title: "SQL JOINs Explained — INNER, LEFT, RIGHT & FULL",
        description: "Visual guide to SQL JOINs with examples. Combine tables, avoid Cartesian products, and practice interview questions.",
        keywords: ["sql joins explained", "sql join tutorial", "inner join left join"],
        category: "Backend",
        readTime: "9 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/sql",
        intro: "JOINs combine rows from multiple tables using related keys. They're the heart of relational queries — and a top SQL interview topic.",
        concepts: ["INNER JOIN — matching rows only", "LEFT JOIN — all left + matches", "RIGHT JOIN — all right + matches", "ON vs WHERE with joins", "Alias tables for readability"],
        code: { lang: "sql", body: `SELECT users.name, orders.total\nFROM users\nINNER JOIN orders ON users.id = orders.user_id;` },
        practice: "Complete SQL JOIN lessons on Sturdee and use the SQL cheat sheet.",
        faq: [{ question: "Most common JOIN?", answer: "INNER JOIN and LEFT JOIN cover 95% of real queries." }],
    },
    {
        slug: "postgresql-vs-mysql-guide",
        title: "PostgreSQL vs MySQL — Which Database Should You Learn?",
        description: "Compare PostgreSQL and MySQL for web development. Features, hosting, JSON support, and job market in 2026.",
        keywords: ["postgresql vs mysql", "learn postgresql", "sql database"],
        category: "Backend",
        readTime: "8 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/sql",
        intro: "Both are open-source relational databases. PostgreSQL leads in features and modern stacks (Supabase, Neon). MySQL remains huge on WordPress and legacy apps.",
        concepts: ["SQL syntax is 90% shared — learn SQL first", "PostgreSQL: JSON, extensions, strict SQL", "MySQL: widespread hosting, simpler ops", "Supabase and Rails often use Postgres", "Pick one and go deep"],
        practice: "Master SQL fundamentals on Sturdee — skills transfer to any database.",
        faq: [{ question: "PostgreSQL for beginners?", answer: "Yes. Slightly steeper hosting setup but better long-term for modern apps." }],
    },
    {
        slug: "rest-api-design-basics",
        title: "REST API Design Basics — Endpoints, Status Codes & JSON",
        description: "Design RESTful APIs: HTTP methods, status codes, resource naming, versioning, and error response patterns.",
        keywords: ["rest api design", "rest api tutorial", "api design basics"],
        category: "Backend",
        readTime: "10 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/javascript/javascript_fetch",
        intro: "REST APIs expose resources via URLs and HTTP verbs. GET /users, POST /users, PATCH /users/1 — predictable patterns every frontend consumes.",
        concepts: ["GET read, POST create, PUT/PATCH update, DELETE remove", "Status: 200 OK, 201 Created, 400 Bad Request, 404 Not Found", "Plural nouns: /articles not /article", "JSON request and response bodies", "Consistent error shape"],
        practice: "Build a simple API with Next.js route handlers after JavaScript fetch lessons on Sturdee.",
        faq: [{ question: "REST vs GraphQL?", answer: "REST is simpler to start. GraphQL when clients need flexible queries at scale." }],
    },
    {
        slug: "git-branching-workflow-guide",
        title: "Git Branching Workflow — feature, main & Pull Requests",
        description: "Git branching strategies for solo devs and teams: main, develop, feature branches, and merge vs rebase.",
        keywords: ["git branching", "git workflow", "feature branch"],
        category: "Backend",
        readTime: "8 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/git",
        intro: "Branches let you work on features without breaking main. The standard flow: branch → commit → push → pull request → merge.",
        concepts: ["main is production-ready", "feature/issue-123-description branches", "Pull request for code review", "Merge commit vs squash merge", "Rebase for linear history (advanced)"],
        practice: "Practice branching in the Git tutorial on Sturdee.",
        faq: [{ question: "Git Flow vs trunk-based?", answer: "Solo/small teams: trunk-based with short feature branches. Enterprise may use Git Flow." }],
    },
    {
        slug: "docker-for-developers-beginners",
        title: "Docker for Developers — Containers Explained Simply",
        description: "Introduction to Docker: images, containers, Dockerfile, and docker-compose for local development.",
        keywords: ["docker for beginners", "learn docker", "docker tutorial"],
        category: "Backend",
        readTime: "10 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/nodejs",
        intro: "Docker packages your app with its dependencies into containers that run identically everywhere — solving 'works on my machine.'",
        concepts: ["Image = blueprint, container = running instance", "Dockerfile defines build steps", "docker-compose for multi-service apps", "Volumes for persistent data", "Not required day one — learn after basics"],
        practice: "Containerize a Node API after completing backend tutorials on Sturdee.",
        faq: [{ question: "Docker required for juniors?", answer: "Nice to have. Learn after you can run apps locally without it." }],
    },
    {
        slug: "api-authentication-jwt-guide",
        title: "API Authentication with JWT — Tokens, Sessions & Security",
        description: "How JWT authentication works for APIs. Access tokens, refresh tokens, and comparison with session cookies.",
        keywords: ["jwt authentication", "api auth tutorial", "json web token"],
        category: "Backend",
        readTime: "9 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/javascript",
        intro: "APIs need to know who is calling. JWTs are signed tokens containing user claims — stateless and popular for SPAs and mobile apps.",
        concepts: ["Login returns signed JWT", "Client sends Authorization: Bearer token", "Server verifies signature", "Refresh tokens for long sessions", "HttpOnly cookies alternative for XSS safety"],
        practice: "Study auth patterns while building projects after JavaScript fundamentals on Sturdee.",
        faq: [{ question: "JWT vs sessions?", answer: "JWTs scale statelessly. Sessions are simpler and easier to revoke." }],
    },
];

export const TOOLS_TOPICS: BlogTopic[] = [
    {
        slug: "vscode-extensions-web-developers",
        title: "Best VS Code Extensions for Web Developers (2026)",
        description: "Essential VS Code extensions: ESLint, Prettier, Tailwind IntelliSense, GitLens, and Live Server for web dev productivity.",
        keywords: ["vscode extensions web development", "best vscode extensions", "vscode for developers"],
        category: "Tools",
        readTime: "7 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials",
        intro: "VS Code dominates web development. The right extensions save hours — auto-formatting, linting, and IntelliSense catch errors before you run code.",
        concepts: ["ESLint + Prettier — code quality", "Tailwind CSS IntelliSense", "GitLens for blame and history", "Error Lens inline errors", "Live Server for static HTML"],
        practice: "Install extensions and use them while coding along with Sturdee tutorials.",
        faq: [{ question: "VS Code vs WebStorm?", answer: "VS Code is free and dominant. WebStorm is paid with deeper refactoring." }],
    },
    {
        slug: "web-performance-core-web-vitals",
        title: "Web Performance & Core Web Vitals — LCP, FID, CLS Explained",
        description: "Improve Core Web Vitals for SEO: Largest Contentful Paint, Interaction to Next Paint, and Cumulative Layout Shift.",
        keywords: ["core web vitals", "web performance seo", "lcp cls"],
        category: "Tools",
        readTime: "9 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/css",
        intro: "Google uses Core Web Vitals as ranking signals. Slow sites lose traffic and conversions. Performance is a developer responsibility, not just ops.",
        concepts: ["LCP — load largest element fast", "INP — interaction responsiveness", "CLS — avoid layout shift", "Optimize images with WebP and lazy load", "Minimize JavaScript bundle size"],
        practice: "Run Lighthouse on Sturdee tutorial pages and fix issues on your own projects.",
        faq: [{ question: "Does speed affect SEO?", answer: "Yes. Core Web Vitals are confirmed ranking factors." }],
    },
    {
        slug: "seo-for-developers-guide",
        title: "SEO for Developers — Technical SEO Checklist",
        description: "Technical SEO developers control: sitemaps, robots.txt, canonical URLs, structured data, and page speed.",
        keywords: ["seo for developers", "technical seo", "developer seo checklist"],
        category: "Tools",
        readTime: "10 min read",
        publishedAt: D,
        tutorialPath: "/resources",
        intro: "Developers implement the technical foundation SEO depends on — crawlable URLs, fast pages, valid metadata, and structured data. Marketing can't fix broken technical SEO.",
        concepts: ["XML sitemap submitted to Search Console", "robots.txt allows crawling", "Unique title and meta description per page", "JSON-LD structured data", "Canonical URLs prevent duplicates"],
        practice: "Read the Sturdee /resources SEO guide and audit your site's sitemap.xml.",
        faq: [{ question: "Do developers need to know SEO?", answer: "Yes for content sites, blogs, and e-commerce. It's part of shipping quality products." }],
    },
    {
        slug: "json-explained-developers",
        title: "JSON Explained for Developers — Syntax, APIs & Parsing",
        description: "What is JSON? Syntax rules, parsing with JSON.parse, stringifying, and using JSON in REST APIs.",
        keywords: ["json explained", "what is json", "json tutorial"],
        category: "Tools",
        readTime: "6 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/javascript",
        intro: "JSON (JavaScript Object Notation) is the universal data format for APIs. Lightweight, human-readable, and supported in every language.",
        concepts: ["Keys must be double-quoted strings", "Values: string, number, boolean, null, array, object", "JSON.parse and JSON.stringify in JS", "No trailing commas", "Content-Type: application/json"],
        code: { lang: "json", body: `{\n  "name": "Sturdee",\n  "lessons": 300,\n  "free": true\n}` },
        practice: "Fetch JSON from an API in the JavaScript fetch tutorial on Sturdee.",
        faq: [{ question: "JSON vs XML?", answer: "JSON won for APIs. XML remains in legacy enterprise systems." }],
    },
    {
        slug: "blockchain-smart-contracts-beginners",
        title: "Blockchain & Smart Contracts for Beginners — Web3 Intro",
        description: "Introduction to blockchain, Ethereum, smart contracts, and Solidity for curious web developers.",
        keywords: ["blockchain beginners", "smart contracts tutorial", "learn solidity"],
        category: "Tools",
        readTime: "10 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/solidity",
        intro: "Blockchain is a distributed ledger. Smart contracts are programs on chain — self-executing when conditions are met. Ethereum popularized programmable blockchains.",
        concepts: ["Bitcoin vs Ethereum", "Wallets and private keys", "Gas fees for transactions", "Solidity for smart contracts", "Test on Sepolia testnet first"],
        practice: "Explore the Solidity tutorial track on Sturdee after JavaScript basics.",
        faq: [{ question: "Do web devs need blockchain?", answer: "Niche but lucrative. Learn after core web fundamentals." }],
    },
    {
        slug: "rust-programming-why-learn",
        title: "Why Learn Rust? — Memory Safety & Systems Programming",
        description: "Why developers learn Rust in 2026: ownership, performance, WASM, and careers at systems companies.",
        keywords: ["learn rust programming", "why rust", "rust tutorial"],
        category: "Tools",
        readTime: "8 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/rust",
        intro: "Rust offers C++ performance with memory safety guarantees — no garbage collector. It's growing in infrastructure, WebAssembly, and blockchain.",
        concepts: ["Ownership and borrowing", "No null — Option type", "Cargo package manager", "WASM and CLI tools", "Steeper learning curve than Python"],
        practice: "Try the Rust intro lessons on Sturdee after comfort with another language.",
        faq: [{ question: "Rust as first language?", answer: "Not recommended. Learn Python or JavaScript first." }],
    },
    {
        slug: "javascript-error-handling-best-practices",
        title: "JavaScript Error Handling — try/catch, Custom Errors & Logging",
        description: "Handle errors in JavaScript properly: try/catch/finally, Error classes, async errors, and user-friendly messages.",
        keywords: ["javascript error handling", "try catch javascript", "javascript errors"],
        category: "JavaScript",
        readTime: "8 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/javascript/javascript_errors",
        intro: "Unhandled errors crash apps and confuse users. Proper error handling separates junior from professional code.",
        concepts: ["try/catch/finally blocks", "throw new Error('message')", "Async errors need try/catch or .catch()", "Custom error classes", "Log server-side, show friendly UI messages"],
        practice: "Complete the JavaScript errors lesson on Sturdee.",
        faq: [{ question: "Should I catch all errors?", answer: "Catch where you can recover or add context. Let unexpected errors bubble in dev." }],
    },
    {
        slug: "dark-mode-css-implementation",
        title: "Dark Mode with CSS — prefers-color-scheme & CSS Variables",
        description: "Implement dark mode using CSS prefers-color-scheme, data attributes, and custom properties without JavaScript flash.",
        keywords: ["dark mode css", "css dark theme", "prefers-color-scheme"],
        category: "CSS",
        readTime: "7 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/css",
        intro: "Users expect dark mode. CSS can respect system preference automatically or toggle via a class on html.",
        concepts: ["@media (prefers-color-scheme: dark)", "CSS variables for theme colors", "data-theme attribute toggle", "color-scheme meta for native controls", "Avoid flash with inline script or SSR"],
        code: { lang: "css", body: `@media (prefers-color-scheme: dark) {\n  :root {\n    --bg: #111;\n    --text: #eee;\n  }\n}` },
        practice: "Add dark mode to a practice page after CSS variables lesson on Sturdee.",
        faq: [{ question: "Dark mode and SEO?", answer: "No direct impact. Improves UX and time-on-site indirectly." }],
    },
    {
        slug: "css-specificity-explained",
        title: "CSS Specificity Explained — Why Your Styles Don't Apply",
        description: "Understand CSS specificity: inline, IDs, classes, elements. Debug conflicts and use !important sparingly.",
        keywords: ["css specificity", "css cascade", "css not working"],
        category: "CSS",
        readTime: "7 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/css",
        intro: "When two rules target the same element, specificity decides the winner — not source order alone. Understanding this saves hours of debugging.",
        concepts: ["Inline styles beat classes", "ID beats class", "Class beats element", "!important overrides (avoid)", "Use devtools Computed tab"],
        practice: "Debug specificity in browser DevTools while doing CSS lessons on Sturdee.",
        faq: [{ question: "How to win specificity wars?", answer: "Increase selector clarity, not !important. Refactor duplicate rules." }],
    },
    {
        slug: "html-aria-accessibility-guide",
        title: "ARIA Accessibility in HTML — Roles, Labels & Live Regions",
        description: "Use ARIA attributes when native HTML isn't enough. aria-label, aria-hidden, roles, and live regions for screen readers.",
        keywords: ["aria accessibility", "html aria", "wcag aria"],
        category: "HTML",
        readTime: "8 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/html",
        intro: "ARIA (Accessible Rich Internet Applications) supplements HTML when native semantics aren't available — but first rule: use native HTML when possible.",
        concepts: ["First choice: semantic HTML", "aria-label when no visible label", "aria-hidden on decorative icons", "role for custom widgets", "aria-live for dynamic updates"],
        practice: "Audit a page with axe DevTools after HTML accessibility lessons on Sturdee.",
        faq: [{ question: "Does ARIA fix bad HTML?", answer: "No. Fix HTML first. ARIA only fills gaps." }],
    },
];
