import type { BlogTopic } from "../types";

const D = "2026-01-15";
const D2 = "2026-02-01";
const D3 = "2026-02-14";
const D4 = "2026-03-01";
const D5 = "2026-03-10";

export const HTML_TOPICS: BlogTopic[] = [
    {
        slug: "what-is-html-semantic-markup-guide",
        title: "What Is HTML Semantic Markup? Complete Guide for Developers",
        description: "Learn HTML semantic elements — header, nav, main, article, section — and why they matter for accessibility, SEO, and maintainable code.",
        keywords: ["html semantic markup", "semantic html", "html5 elements guide"],
        category: "HTML",
        readTime: "8 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/html",
        intro: "Semantic HTML uses elements that describe meaning, not just appearance. A <nav> tells browsers and screen readers 'this is navigation.' A <div class='nav'> does not. Search engines and assistive technology rely on semantics to understand your page structure.",
        concepts: ["<header>, <nav>, <main>, <article>, <section>, <aside>, <footer>", "One <main> per page for primary content", "Heading hierarchy: single <h1>, nested h2–h6", "Landmark roles improve screen reader navigation", "Semantic HTML supports rich snippets in Google"],
        code: { lang: "html", title: "Semantic page skeleton", body: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>My Page</title>\n</head>\n<body>\n  <header><nav>...</nav></header>\n  <main>\n    <article>\n      <h1>Page Title</h1>\n      <p>Content here.</p>\n    </article>\n  </main>\n  <footer>...</footer>\n</body>\n</html>` },
        mistakes: ["Using <div> for everything", "Skipping heading levels (h1 to h4)", "Multiple <main> elements", "Empty alt attributes on informative images"],
        practice: "Work through the free HTML tutorial on Sturdee — start with elements and semantics, then build a semantic landing page.",
        faq: [{ question: "Is semantic HTML required?", answer: "Not strictly, but it improves SEO, accessibility scores, and code readability — all ranking factors for education sites." }],
    },
    {
        slug: "html-forms-accessibility-best-practices",
        title: "HTML Forms & Accessibility — Best Practices (2026)",
        description: "Build accessible HTML forms with labels, ARIA, validation messages, and keyboard navigation. WCAG-compliant patterns for developers.",
        keywords: ["html forms accessibility", "accessible forms", "wcag forms"],
        category: "HTML",
        readTime: "9 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/html/html_forms",
        intro: "Forms are where users convert — sign up, checkout, contact. Inaccessible forms lose users and violate WCAG. Every input needs a programmatic label, clear errors, and keyboard support.",
        concepts: ["Associate <label for='id'> with inputs", "Use required and aria-required appropriately", "Group related fields with <fieldset> and <legend>", "Error messages linked via aria-describedby", "Never rely on placeholder as the only label"],
        steps: ["Add explicit <label> for every input", "Use correct input types (email, tel, date)", "Show validation errors next to fields", "Test tab order with keyboard only", "Run axe or Lighthouse accessibility audit"],
        mistakes: ["Placeholder-only labels", "Disabled submit with no explanation", "CAPTCHA without audio alternative"],
        practice: "Practice form markup in the HTML forms lesson on Sturdee, then audit a real form with browser DevTools.",
        faq: [{ question: "Do all inputs need visible labels?", answer: "Yes, unless an alternative visible text is programmatically associated. Placeholders are not labels." }],
    },
    {
        slug: "html-seo-meta-tags-guide",
        title: "HTML Meta Tags for SEO — Title, Description & Open Graph",
        description: "Essential HTML meta tags for SEO: title, description, canonical, robots, Open Graph, and Twitter cards explained for developers.",
        keywords: ["html meta tags seo", "meta description", "open graph tags"],
        category: "HTML",
        readTime: "7 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/html/html_syntax",
        intro: "Meta tags live in <head> and tell search engines how to index and display your page. A strong title and description directly affect click-through rate from Google — often more than position alone.",
        concepts: ["<title> — 50–60 characters, unique per page", "<meta name='description'> — 150–160 characters", "<link rel='canonical'> prevents duplicate content", "og:title, og:description, og:image for social sharing", "robots meta for noindex when needed"],
        code: { lang: "html", body: `<head>\n  <title>Learn JavaScript Free — Sturdee Tutorial</title>\n  <meta name="description" content="Free JavaScript tutorial with interactive lessons.">\n  <link rel="canonical" href="https://www.sturdee.online/tutorials/javascript">\n</head>` },
        practice: "Inspect meta tags on Sturdee tutorial pages, then add proper head elements to your own project.",
        faq: [{ question: "Does meta keywords still matter?", answer: "Google ignores meta keywords. Focus on title, description, and quality content." }],
    },
    {
        slug: "responsive-html-mobile-first",
        title: "Responsive HTML & Mobile-First Structure",
        description: "Mobile-first HTML structure: viewport meta, responsive images, picture element, and semantic layout for phones and tablets.",
        keywords: ["responsive html", "mobile first html", "viewport meta tag"],
        category: "HTML",
        readTime: "8 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/html",
        intro: "Over 60% of web traffic is mobile. Responsive HTML starts with the viewport meta tag and structured content that reflows gracefully before CSS even loads.",
        concepts: ["<meta name='viewport' content='width=device-width, initial-scale=1'>", "<picture> and srcset for responsive images", "Logical DOM order matches visual priority", "Touch-friendly tap targets (44px minimum)", "Avoid horizontal scroll from wide tables"],
        mistakes: ["Missing viewport meta", "Fixed-width tables on mobile", "Tiny click targets"],
        practice: "Complete HTML layout lessons on Sturdee, then pair with the CSS responsive design tutorial.",
        faq: [{ question: "Is mobile-first HTML or CSS?", answer: "Both. HTML provides structure; CSS media queries adapt layout. Start mobile structure first." }],
    },
    {
        slug: "html-tables-data-guide",
        title: "HTML Tables for Data — thead, tbody & Accessibility",
        description: "When and how to use HTML tables for tabular data. Scope attributes, captions, and responsive table patterns.",
        keywords: ["html tables", "html table accessibility", "data tables html"],
        category: "HTML",
        readTime: "6 min read",
        publishedAt: D5,
        tutorialPath: "/tutorials/html/html_tables",
        intro: "Tables are for tabular data only — not page layout. Proper table markup helps screen readers announce column and row headers correctly.",
        concepts: ["<caption> describes the table", "scope='col' and scope='row' on <th>", "thead, tbody, tfoot structure", "Use CSS for layout, not tables"],
        practice: "Build an accessible pricing table after the HTML tables lesson on Sturdee.",
        faq: [{ question: "Should I use tables for layout?", answer: "No. Use CSS Grid or Flexbox. Tables are for data relationships." }],
    },
];

export const CSS_TOPICS: BlogTopic[] = [
    {
        slug: "css-flexbox-complete-guide",
        title: "CSS Flexbox Complete Guide — Align, Justify & Build Layouts",
        description: "Master CSS Flexbox: flex-direction, justify-content, align-items, gap, and wrap. Build navbars, cards, and centered layouts.",
        keywords: ["css flexbox guide", "flexbox tutorial", "learn flexbox"],
        category: "CSS",
        readTime: "10 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/css/css_layout",
        intro: "Flexbox is a one-dimensional layout system — perfect for navbars, toolbars, card rows, and vertically centering content. It replaced float hacks for most UI patterns.",
        concepts: ["display: flex on parent", "flex-direction: row | column", "justify-content — main axis alignment", "align-items — cross axis alignment", "gap replaces margin hacks", "flex: 1 for growing children"],
        code: { lang: "css", body: `.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 1rem;\n}` },
        steps: ["Set display:flex on container", "Choose row or column direction", "Align and justify", "Use gap for spacing", "Let items grow with flex:1"],
        practice: "Follow the CSS layout tutorial on Sturdee and rebuild a navbar with Flexbox.",
        faq: [{ question: "Flexbox or Grid?", answer: "Flexbox for one-dimensional layouts (rows OR columns). Grid for two-dimensional page layouts." }],
    },
    {
        slug: "css-grid-layout-tutorial",
        title: "CSS Grid Layout Tutorial — Templates, Gaps & Areas",
        description: "Learn CSS Grid: grid-template-columns, fr units, grid-template-areas, and responsive grids without media queries.",
        keywords: ["css grid tutorial", "css grid layout", "learn css grid"],
        category: "CSS",
        readTime: "11 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/css/css_layout",
        intro: "CSS Grid handles two-dimensional layouts — full page structures, dashboards, and photo galleries. It's the modern replacement for complex float and positioning layouts.",
        concepts: ["grid-template-columns: repeat(3, 1fr)", "gap for row and column spacing", "grid-template-areas for named layouts", "minmax() for responsive columns", "grid-column and grid-row spanning"],
        code: { lang: "css", body: `.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 1.5rem;\n}` },
        practice: "Build a responsive card grid using the CSS tutorial on Sturdee.",
        faq: [{ question: "Can I use Grid and Flexbox together?", answer: "Yes. Grid for page layout; Flexbox inside grid cells for component internals." }],
    },
    {
        slug: "css-responsive-design-breakpoints",
        title: "CSS Responsive Design — Breakpoints & Mobile-First Media Queries",
        description: "Responsive CSS with mobile-first media queries, breakpoints, clamp(), and container queries for modern layouts.",
        keywords: ["css responsive design", "css breakpoints", "media queries"],
        category: "CSS",
        readTime: "9 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/css",
        intro: "Responsive design means your UI works on watches, phones, tablets, and ultrawide monitors. Mobile-first CSS starts with base styles for small screens, then adds min-width breakpoints.",
        concepts: ["@media (min-width: 768px) mobile-first", "Common breakpoints: 640, 768, 1024, 1280", "clamp() for fluid typography", "container queries for component-level responsiveness", "Relative units: rem, %, vw"],
        mistakes: ["Desktop-first then max-width hacks", "Too many breakpoints", "Fixed pixel widths on containers"],
        practice: "Complete the CSS responsive lesson track on Sturdee.",
        faq: [{ question: "What breakpoint should I use?", answer: "Let content break naturally. Common: 768px tablet, 1024px desktop. Test your actual layout." }],
    },
    {
        slug: "css-variables-custom-properties",
        title: "CSS Variables (Custom Properties) — Theming & Design Tokens",
        description: "Use CSS custom properties for colors, spacing, and themes. Dark mode and design system patterns.",
        keywords: ["css variables", "css custom properties", "css design tokens"],
        category: "CSS",
        readTime: "7 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/css/css_variables",
        intro: "CSS variables (--color-primary) let you define reusable values and switch themes at runtime — essential for dark mode and design systems.",
        concepts: [":root for global tokens", "var(--name, fallback)", "Scoped variables on components", "Dark mode via prefers-color-scheme or data-theme", "Works with calc()"],
        code: { lang: "css", body: `:root {\n  --color-primary: #10B981;\n  --space-md: 1rem;\n}\n.button {\n  background: var(--color-primary);\n  padding: var(--space-md);\n}` },
        practice: "Study CSS variables on Sturdee, then add a dark mode toggle to a practice page.",
        faq: [{ question: "CSS variables vs Sass variables?", answer: "CSS variables are live in the browser and can change at runtime. Sass variables compile away." }],
    },
    {
        slug: "tailwind-css-vs-traditional-css",
        title: "Tailwind CSS vs Traditional CSS — When to Use Each",
        description: "Compare Tailwind utility-first CSS with traditional stylesheets. Pros, cons, and learning path for 2026 developers.",
        keywords: ["tailwind css vs css", "utility first css", "tailwind tutorial"],
        category: "CSS",
        readTime: "8 min read",
        publishedAt: D5,
        tutorialPath: "/tutorials/css",
        intro: "Tailwind CSS applies styles via utility classes (flex, p-4, text-emerald-600) instead of writing custom CSS files. Sturdee itself uses Tailwind-style utility patterns. Understanding traditional CSS first makes Tailwind far easier.",
        concepts: ["Learn CSS fundamentals before Tailwind", "Utilities speed prototyping", "Traditional CSS better for complex animations", "Tailwind + component extraction at scale", "@apply for repeated patterns"],
        practice: "Master CSS on Sturdee first, then explore Tailwind in a side project.",
        faq: [{ question: "Should beginners start with Tailwind?", answer: "Learn HTML and CSS basics first. Tailwind makes sense once you understand what the utilities do." }],
    },
    {
        slug: "css-animations-transitions-guide",
        title: "CSS Animations & Transitions — Smooth UI Motion",
        description: "CSS transition and @keyframes animation guide. Transform, opacity, and performance best practices.",
        keywords: ["css animations", "css transitions", "css transform"],
        category: "CSS",
        readTime: "8 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/css/css_transitions",
        intro: "Subtle motion guides attention — button hovers, modal entrances, loading states. CSS transitions handle simple state changes; @keyframes handle complex sequences.",
        concepts: ["transition: property duration easing", "transform and opacity are GPU-friendly", "@keyframes for looping animations", "prefers-reduced-motion for accessibility", "Avoid animating width/height (use transform)"],
        practice: "Try the CSS transitions lesson on Sturdee and animate a card hover effect.",
        faq: [{ question: "CSS or JavaScript animation?", answer: "CSS for simple UI transitions. JavaScript (or libraries) for complex choreographed sequences." }],
    },
];
