import type { BlogTopic } from "../types";

const D = "2026-01-20";
const D2 = "2026-02-05";
const D3 = "2026-02-18";
const D4 = "2026-03-05";
const D5 = "2026-03-15";

export const JAVASCRIPT_TOPICS: BlogTopic[] = [
    {
        slug: "javascript-closures-explained",
        title: "JavaScript Closures Explained — Simple Guide with Examples",
        description: "Understand JavaScript closures: lexical scope, inner functions, and practical use cases in React, callbacks, and modules.",
        keywords: ["javascript closures", "closures explained", "javascript scope"],
        category: "JavaScript",
        readTime: "9 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/javascript/javascript_functions",
        intro: "A closure is when an inner function remembers variables from its outer scope even after the outer function has finished. Closures power callbacks, event handlers, React hooks, and module patterns.",
        concepts: ["Lexical scope — functions see where they were defined", "Inner function closes over outer variables", "Used in debounce, throttle, and factories", "Common in interview questions", "let/const block scope affects closures"],
        code: { lang: "javascript", body: `function makeCounter() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nconst counter = makeCounter();\ncounter(); // 1\ncounter(); // 2` },
        practice: "Study functions and scope in the JavaScript tutorial on Sturdee, then implement a debounce utility.",
        faq: [{ question: "Are closures memory leaks?", answer: "Only if you hold references unnecessarily. They're a feature, not a bug." }],
    },
    {
        slug: "javascript-async-await-guide",
        title: "JavaScript Async/Await — Complete Guide for Beginners",
        description: "Master async/await, Promises, and fetch in JavaScript. Handle API calls, errors, and parallel requests.",
        keywords: ["javascript async await", "javascript promises", "async javascript tutorial"],
        category: "JavaScript",
        readTime: "10 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/javascript/javascript_async",
        intro: "JavaScript is single-threaded but non-blocking. Async/await lets you write asynchronous code that reads like synchronous code — essential for fetch, databases, and timers.",
        concepts: ["Promises represent future values", "async function always returns a Promise", "await pauses until Promise resolves", "try/catch for async errors", "Promise.all for parallel requests"],
        code: { lang: "javascript", body: `async function loadUser(id) {\n  try {\n    const res = await fetch(\`/api/users/\${id}\`);\n    if (!res.ok) throw new Error('Failed');\n    return await res.json();\n  } catch (err) {\n    console.error(err);\n  }\n}` },
        practice: "Complete the async/await lessons on Sturdee, then build a weather app with fetch.",
        faq: [{ question: "async/await vs .then()?", answer: "Same underlying Promises. async/await is cleaner for sequential logic." }],
    },
    {
        slug: "javascript-es6-features-guide",
        title: "JavaScript ES6+ Features Every Developer Should Know",
        description: "Arrow functions, destructuring, spread, template literals, modules, and let/const — modern JavaScript essentials.",
        keywords: ["javascript es6", "modern javascript", "es6 features"],
        category: "JavaScript",
        readTime: "11 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/javascript",
        intro: "ES6 (2015) and later releases transformed JavaScript into a modern language. If you're still using var and function-only syntax, you're missing tools every codebase expects.",
        concepts: ["let and const block scoping", "Arrow functions and lexical this", "Destructuring arrays and objects", "Spread ... and rest parameters", "Template literals and modules import/export"],
        practice: "Work through JavaScript syntax lessons on Sturdee from variables through modules.",
        faq: [{ question: "Should I still learn var?", answer: "Recognize it in legacy code. Use const by default and let when reassigning." }],
    },
    {
        slug: "javascript-array-methods-map-filter",
        title: "JavaScript Array Methods — map, filter, reduce Explained",
        description: "Functional array methods in JavaScript: map, filter, reduce, find, and some. Real examples for data transformation.",
        keywords: ["javascript map filter reduce", "javascript array methods", "array map tutorial"],
        category: "JavaScript",
        readTime: "9 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/javascript/javascript_arrays",
        intro: "Arrays are the most common data structure in JavaScript. Functional methods let you transform data without manual for-loops — cleaner and less error-prone.",
        concepts: ["map — transform each element", "filter — keep matching elements", "reduce — accumulate to single value", "find / findIndex for search", "Chaining methods"],
        code: { lang: "javascript", body: `const users = [{name:'Alex',score:90},{name:'Sam',score:75}];\nconst top = users\n  .filter(u => u.score >= 80)\n  .map(u => u.name);` },
        practice: "Practice arrays in the Sturdee JavaScript tutorial track.",
        faq: [{ question: "map vs forEach?", answer: "map returns a new array. forEach returns undefined — use for side effects only." }],
    },
    {
        slug: "javascript-dom-manipulation-guide",
        title: "JavaScript DOM Manipulation — Select, Modify & Events",
        description: "Query the DOM with querySelector, update content, classes, and handle click/submit events in vanilla JavaScript.",
        keywords: ["javascript dom", "dom manipulation", "javascript events"],
        category: "JavaScript",
        readTime: "10 min read",
        publishedAt: D5,
        tutorialPath: "/tutorials/javascript/javascript_dom",
        intro: "The DOM is the browser's tree representation of your HTML. JavaScript can select elements, change text, toggle classes, and respond to user events — the foundation before React.",
        concepts: ["document.querySelector and querySelectorAll", "textContent vs innerHTML", "classList.add/remove/toggle", "addEventListener for events", "event.preventDefault on forms"],
        practice: "Build a todo list after the DOM lessons on Sturdee.",
        faq: [{ question: "DOM vs React?", answer: "React abstracts the DOM. Understanding vanilla DOM helps you debug and learn React faster." }],
    },
    {
        slug: "javascript-fetch-api-tutorial",
        title: "JavaScript Fetch API Tutorial — GET, POST & Error Handling",
        description: "Use fetch() to call REST APIs in JavaScript. JSON parsing, headers, POST bodies, and CORS basics.",
        keywords: ["javascript fetch api", "fetch tutorial", "javascript api calls"],
        category: "JavaScript",
        readTime: "8 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/javascript/javascript_fetch",
        intro: "fetch is the modern browser API for HTTP requests. Every full-stack app uses it — or libraries built on top of it like axios.",
        concepts: ["fetch(url) returns a Promise", "res.ok and res.status checks", "await res.json() for JSON bodies", "POST with method, headers, body", "CORS is a browser security feature"],
        code: { lang: "javascript", body: `const res = await fetch('/api/data', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ name: 'Sturdee' })\n});` },
        practice: "Complete the fetch lesson on Sturdee and connect to a public API.",
        faq: [{ question: "fetch vs axios?", answer: "fetch is built-in. axios adds interceptors and nicer defaults — both are fine." }],
    },
    {
        slug: "typescript-vs-javascript-guide",
        title: "TypeScript vs JavaScript — Should You Learn TypeScript in 2026?",
        description: "Compare TypeScript and JavaScript. Types, tooling, job market, and when to add TypeScript to your stack.",
        keywords: ["typescript vs javascript", "learn typescript", "typescript 2026"],
        category: "JavaScript",
        readTime: "8 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/typescript",
        intro: "TypeScript adds static types to JavaScript. It catches bugs at compile time and powers better IDE autocomplete — which is why most professional frontends use it.",
        concepts: ["JavaScript is the runtime; TypeScript compiles to JS", "Types for function params and return values", "Interfaces and type aliases", "Gradual adoption — rename .js to .ts", "Dominant in React and Node enterprise codebases"],
        practice: "Learn JavaScript on Sturdee first, then start the TypeScript tutorial track.",
        faq: [{ question: "Can beginners skip JavaScript?", answer: "No. TypeScript is a superset. Learn JS fundamentals first." }],
    },
    {
        slug: "react-hooks-explained-beginners",
        title: "React Hooks Explained for Beginners — useState & useEffect",
        description: "Understand React hooks: useState for state, useEffect for side effects, and rules of hooks for functional components.",
        keywords: ["react hooks explained", "usestate useeffect", "react hooks tutorial"],
        category: "JavaScript",
        readTime: "10 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/javascript",
        intro: "Hooks let functional React components use state and lifecycle features. useState and useEffect are the two you'll use daily.",
        concepts: ["useState returns [value, setter]", "State updates trigger re-renders", "useEffect runs after render", "Dependency array controls effect timing", "Only call hooks at top level"],
        practice: "Master JavaScript and DOM first on Sturdee, then explore React in a Next.js project.",
        faq: [{ question: "Are class components dead?", answer: "Most new code uses hooks. You may see classes in legacy apps." }],
    },
    {
        slug: "nodejs-beginners-guide",
        title: "Node.js for Beginners — Run JavaScript on the Server",
        description: "Introduction to Node.js: npm, modules, file system, and building your first API with Express or Next.js.",
        keywords: ["nodejs beginners", "learn nodejs", "node.js tutorial"],
        category: "JavaScript",
        readTime: "11 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/nodejs",
        intro: "Node.js runs JavaScript outside the browser — powering APIs, CLIs, and build tools. If you know JavaScript, you're halfway to backend development.",
        concepts: ["V8 engine + libuv for async I/O", "npm for package management", "CommonJS vs ES modules", "fs, path, http built-in modules", "Express or Next.js for HTTP servers"],
        practice: "Follow the Node.js tutorial track on Sturdee after JavaScript fundamentals.",
        faq: [{ question: "Node.js vs Deno vs Bun?", answer: "Node has the largest ecosystem. Deno and Bun are newer alternatives with different tradeoffs." }],
    },
    {
        slug: "nextjs-app-router-guide",
        title: "Next.js App Router Guide — Server Components & Routing",
        description: "Learn Next.js App Router: file-based routing, layouts, server components, and data fetching in 2026.",
        keywords: ["nextjs app router", "next.js tutorial", "react server components"],
        category: "Tools",
        readTime: "12 min read",
        publishedAt: D5,
        tutorialPath: "/tutorials/javascript",
        intro: "Next.js App Router (app/ directory) is the default for new React projects. Server Components reduce client JavaScript and improve SEO — critical for education sites like Sturdee.",
        concepts: ["app/page.tsx = route", "layout.tsx wraps children", "Server vs Client Components", "generateMetadata for SEO", "Server Actions for forms"],
        practice: "Build a blog or portfolio with Next.js after completing JavaScript on Sturdee.",
        faq: [{ question: "Pages Router vs App Router?", answer: "App Router is the future. New projects should use app/." }],
    },
];
