import type { BlogTopic } from "../types";

const D = "2026-01-22";
const D2 = "2026-02-08";
const D3 = "2026-02-20";
const D4 = "2026-03-08";

export const PYTHON_TOPICS: BlogTopic[] = [
    {
        slug: "python-list-comprehensions-guide",
        title: "Python List Comprehensions — Clean Data Transformation",
        description: "Python list comprehensions syntax, examples, and when to use them vs loops. Includes dict and set comprehensions.",
        keywords: ["python list comprehension", "python comprehensions", "python lists"],
        category: "Python",
        readTime: "7 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/python/python_lists",
        intro: "List comprehensions compress loop + append into one readable line. They're idiomatic Python and appear in every professional codebase.",
        concepts: ["[expr for item in iterable]", "Add if for filtering", "Nested comprehensions sparingly", "Dict and set comprehensions", "Readability over cleverness"],
        code: { lang: "python", body: `squares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]` },
        practice: "Study Python lists and loops on Sturdee, then refactor loops to comprehensions.",
        faq: [{ question: "Are comprehensions faster?", answer: "Often slightly faster than loops. Main benefit is readability." }],
    },
    {
        slug: "python-virtual-environments-guide",
        title: "Python Virtual Environments — venv, pip & Dependencies",
        description: "Set up Python virtual environments with venv. Install packages, requirements.txt, and project isolation.",
        keywords: ["python virtual environment", "python venv", "pip install"],
        category: "Python",
        readTime: "8 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/python",
        intro: "Virtual environments isolate project dependencies so Project A's Django version doesn't break Project B. Every Python project should use one.",
        concepts: ["python -m venv .venv", "Activate: source .venv/bin/activate", "pip install package", "pip freeze > requirements.txt", "Never install globally for projects"],
        steps: ["Create venv", "Activate", "pip install dependencies", "Freeze requirements.txt", "Add .venv to .gitignore"],
        practice: "Set up venv while following the Python intro tutorial on Sturdee.",
        faq: [{ question: "venv vs conda?", answer: "venv is built-in and enough for most web projects. Conda shines for data science." }],
    },
    {
        slug: "python-django-vs-flask",
        title: "Django vs Flask — Which Python Web Framework?",
        description: "Compare Django and Flask for Python web development. Batteries-included vs microframework tradeoffs.",
        keywords: ["django vs flask", "python web framework", "learn django"],
        category: "Python",
        readTime: "9 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/python",
        intro: "Django ships batteries included — ORM, admin, auth. Flask is minimal and flexible. Your choice depends on project size and team preferences.",
        concepts: ["Django — full-stack, opinionated, fast to ship CRUD", "Flask — micro, choose your own ORM", "Both production-proven", "Learn Python fundamentals first", "FastAPI rising for APIs"],
        practice: "Complete Python OOP and functions on Sturdee before picking a framework.",
        faq: [{ question: "Which for beginners?", answer: "Flask is simpler to start. Django teaches structure faster for full apps." }],
    },
    {
        slug: "python-data-types-explained",
        title: "Python Data Types Explained — int, str, list, dict & More",
        description: "Python built-in types: numbers, strings, lists, tuples, dicts, sets. Mutability and type checking.",
        keywords: ["python data types", "python types", "python dict list"],
        category: "Python",
        readTime: "8 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/python/python_syntax",
        intro: "Python's dynamic typing means variables reference objects of any type. Understanding mutability and core types prevents subtle bugs.",
        concepts: ["int, float, bool", "str — immutable text", "list — mutable ordered", "tuple — immutable ordered", "dict — key-value mapping", "set — unique unordered"],
        practice: "Work through Python syntax and data types on Sturdee interactively.",
        faq: [{ question: "list vs tuple?", answer: "Use list when you need to change data. Tuple for fixed records and dict keys." }],
    },
    {
        slug: "python-automation-scripts-guide",
        title: "Python Automation Scripts — Automate Boring Tasks",
        description: "Write Python scripts to automate files, CSVs, emails, and APIs. pathlib, csv, and requests basics.",
        keywords: ["python automation", "python scripts", "automate with python"],
        category: "Python",
        readTime: "9 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/python",
        intro: "Python dominates automation — rename files, parse CSVs, hit APIs, schedule cron jobs. It's often the fastest path to useful scripts.",
        concepts: ["pathlib for file paths", "csv module for spreadsheets", "requests for HTTP", "argparse for CLI args", "Schedule with cron or Task Scheduler"],
        practice: "Build a file renamer script after Python basics on Sturdee.",
        faq: [{ question: "Python 2 or 3?", answer: "Python 3 only. Python 2 is end-of-life." }],
    },
    {
        slug: "learn-python-web-development",
        title: "Learn Python for Web Development — Complete Path",
        description: "Roadmap to learn Python for web backends: syntax, Flask/Django, databases, and deployment.",
        keywords: ["python web development", "learn python backend", "python web tutorial"],
        category: "Python",
        readTime: "10 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/python",
        intro: "Python powers Instagram, Dropbox backends, and countless APIs. The path: core Python → web framework → database → deploy.",
        steps: ["Python syntax and functions on Sturdee", "OOP and error handling", "Pick Flask or Django", "Add PostgreSQL and SQL", "Deploy to Railway or Render"],
        practice: "Start the free Python tutorial on Sturdee — 18+ interactive lessons.",
        faq: [{ question: "Python or Node for backend?", answer: "Both hire well. Python wins in data/ML adjacency; Node in full-stack JS teams." }],
    },
];

export const SHOPIFY_TOPICS: BlogTopic[] = [
    {
        slug: "shopify-liquid-basics-guide",
        title: "Shopify Liquid Basics — Tags, Objects & Filters",
        description: "Learn Shopify Liquid templating: output tags, logic tags, objects like product and collection, and filters.",
        keywords: ["shopify liquid basics", "learn liquid shopify", "liquid template language"],
        category: "Shopify",
        readTime: "10 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/liquid",
        intro: "Liquid is Shopify's template language for themes. It separates logic from HTML so merchants can customize stores safely without arbitrary code execution.",
        concepts: ["{{ output }} tags", "{% logic %} tags", "Objects: product, collection, cart", "Filters: | money, | img_url", "theme.liquid layout file"],
        practice: "Complete the 46-lesson Liquid tutorial on Sturdee — the most comprehensive free track online.",
        faq: [{ question: "Liquid vs Twig?", answer: "Similar syntax. Liquid is Shopify-specific with commerce objects." }],
    },
    {
        slug: "shopify-theme-customization-guide",
        title: "Shopify Theme Customization — Sections, JSON Templates & OS 2.0",
        description: "Customize Shopify Online Store 2.0 themes with sections, blocks, JSON templates, and the theme editor.",
        keywords: ["shopify theme customization", "shopify os 2.0", "shopify sections"],
        category: "Shopify",
        readTime: "11 min read",
        publishedAt: D2,
        tutorialPath: "/tutorials/liquid",
        intro: "Online Store 2.0 lets merchants add and rearrange sections without code. Developers build reusable sections with schema JSON.",
        concepts: ["sections/*.liquid + schema", "JSON templates in templates/", "Blocks inside sections", "settings in schema", "Dawn theme as reference"],
        practice: "Study Liquid sections on Sturdee, then clone Dawn and add a custom section.",
        faq: [{ question: "Vintage vs OS 2.0?", answer: "All new themes should be OS 2.0. Vintage themes lack JSON templates." }],
    },
    {
        slug: "shopify-cli-setup-guide",
        title: "Shopify CLI Setup Guide — theme dev, check & push",
        description: "Install Shopify CLI, run shopify theme dev, theme check linting, and deploy themes to stores.",
        keywords: ["shopify cli setup", "shopify theme dev", "shopify cli install"],
        category: "Shopify",
        readTime: "9 min read",
        publishedAt: D3,
        tutorialPath: "/tutorials/liquid/cli",
        intro: "Shopify CLI is the official toolchain for theme development — local preview, hot reload, linting, and deployment from your terminal.",
        steps: ["Install Node 22+ and Git", "npm install -g @shopify/cli", "shopify theme init", "shopify theme dev --store your-store", "shopify theme check before push"],
        practice: "Follow the Shopify CLI install tutorial on Sturdee for Windows, Mac, and Linux.",
        faq: [{ question: "CLI vs Theme Kit?", answer: "Theme Kit is legacy. Use Shopify CLI for all new theme work." }],
    },
    {
        slug: "shopify-sections-blocks-explained",
        title: "Shopify Sections & Blocks — Theme Architecture Explained",
        description: "How Shopify sections and blocks work in theme architecture. Schema, presets, and dynamic sources.",
        keywords: ["shopify sections blocks", "shopify theme architecture", "shopify schema"],
        category: "Shopify",
        readTime: "8 min read",
        publishedAt: D4,
        tutorialPath: "/tutorials/liquid",
        intro: "Sections are reusable page components. Blocks are sub-components merchants configure inside sections — like slides in a slideshow.",
        concepts: ["{% schema %} JSON defines settings", "blocks array in schema", "{% for block in section.blocks %}", "Presets for theme editor", "App blocks for apps"],
        practice: "Build a testimonial section with blocks in the Liquid tutorial on Sturdee.",
        faq: [{ question: "How many blocks per section?", answer: "Define max_blocks in schema. Keep UX manageable — usually under 10." }],
    },
    {
        slug: "shopify-liquid-filters-objects",
        title: "Shopify Liquid Filters & Objects — Reference for Theme Devs",
        description: "Essential Liquid filters and objects for Shopify themes: product, cart, money filters, and date formatting.",
        keywords: ["shopify liquid filters", "liquid objects shopify", "shopify liquid reference"],
        category: "Shopify",
        readTime: "9 min read",
        publishedAt: D,
        tutorialPath: "/tutorials/liquid",
        intro: "Objects hold data (product.title). Filters transform output (| money). Together they render dynamic storefronts.",
        concepts: ["product, variant, collection, cart objects", "| money, | img_url, | escape filters", "default filter for fallbacks", "paginate for collections", "link_to for URLs"],
        practice: "Use the Shopify Liquid cheat sheet and tutorial on Sturdee while building a product card.",
        faq: [{ question: "Where is Liquid documented?", answer: "Shopify dev docs + Sturdee's 46-lesson Liquid track." }],
    },
];
